### ISSUE TITLE
Unable to sort columns in Yields tab of Reports screen.

### ISSUE THREAD

**Issue by camk16** [Azurency/CQUI_Community-Edition#11]
![untitled](https://user-images.githubusercontent.com/30790283/30238281-4a1b410c-9501-11e7-9f49-409984b2a051.png)

**Comment by Azurency** [comment]
I'm looking into this

**Comment by Azurency** [comment]
It might come from this line https://github.com/Azurency/CQUI_Community-Edition/blob/f996645d8354881dd75e275445cc55b22e4cd5fb/Integrations/URS/reportscreen.lua#L1022
Will test it later today
