### ISSUE TITLE
Unit path showing stay after moving a unit

### ISSUE THREAD

**Issue by Azurency** [Azurency/CQUI_Community-Edition#13]
![pasted image at 2017_09_07 11_48 pm](https://user-images.githubusercontent.com/8012430/30238524-14184d14-9549-11e7-9fac-28f6354f6634.png)
When set a unit to go somewhere the path is shown correctly but when you cancel that movement by selecting it and moving the unit, the old path is still showing

**Comment by sparrow8332** [comment]
might be a better idea to remove the unit path altogether as civ has its own version now.

**Comment by Azurency** [comment]
Now the mod use the new vanilla `RealizeMovementPath(true)` on hover of the unitflag instead of the custom cqui implementation.
