### ISSUE TITLE
Simplified Gossip: Strange messages (Japanese)

### ISSUE THREAD

**Issue by 8h42** [Azurency/CQUI_Community-Edition#132]
Hello again.
Thank you for the update.
Now the UI doesn't disappear.

This time I used my translation mod, but Simplified Gossip did not work properly for me.

1. Japanese flavour texts (ex. `LOC_GOSSIP_SOURCE_DELEGATE`, `LOC_GOSSIP_SOURCE_TRAIT`) are not removed. 
![1 main_screen](https://user-images.githubusercontent.com/11933188/30854649-3f31b5d8-a2ed-11e7-8303-7b444f4f4301.jpg)

2. Gossip messages don't show up in the diplomatic screen.
![2 diplomatic_screen](https://user-images.githubusercontent.com/11933188/30854657-43c846a2-a2ed-11e7-925e-9c0e249c7530.jpg)

Do you have any ideas?

Active mods:

- Community Quick User Interface - CQUI (2017.09.25)
- Community Quick User Interface - CQUI (JP)
[Active mods.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1332677/Active.mods.zip)

Save file:
[_test_2017.09.26_France.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1332679/_test_2017.09.26_France.zip)

Log file:
[Logs_2017.09.26_France.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1332681/Logs_2017.09.26_France.zip)

**Comment by Azurency** [comment]
Well, still a space problem, I fixed it

**Comment by 8h42** [comment]
I tried the latest CQUI_Community-Edition-master.
Now flavour texts are removed and the diplomatic screen works properly!
![ss](https://user-images.githubusercontent.com/11933188/30885414-2045f8e4-a34e-11e7-99b7-400622c24759.png)

However, Gossip messages don't show up in the main screen (map screen?) at all.


Active mods:
- CQUI_Community-Edition-master
- Community Quick User Interface - CQUI (JP)
[Active mods_2017.09.27.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1335078/Active.mods_2017.09.27.zip)

Save file:
[_test_2017.09.27_France.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1335079/_test_2017.09.27_France.zip)

Log file:
[Logs_2017.09.27_France.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1335081/Logs_2017.09.27_France.zip)

**Comment by Azurency** [comment]
Well, again spaces issues in `CQUI_IsGossipMessageIgnored` I should review this, it's expecting sentences like in English that not a right way to code.

**Comment by Azurency** [comment]
It should work now, I use patterns to check if a gossip message is ignored or not, and no longer count words.

**Comment by 8h42** [comment]
It works perfectly!
Thank you for your hard work.
