### ISSUE TITLE
Tech / Civic Popups Not working 

### ISSUE THREAD

**Issue by sparrow8332** [Azurency/CQUI_Community-Edition#134]
Enable / Disable whatever the option popups for civic or tech or both do not show on completion off a tech or civic

**Comment by ricanuck** [comment]
Not sure I understand what you are saying... it is working fine for me, I have tech and civic popups on but sound off (yes, shoot me, Sean finally got on my nerves... :))) ).

**Comment by sparrow8332** [comment]
it was brought to my attention by a youtuber / twith streamer quill18 - i started a new game ticked the options to show popups for tech and civic but nothing shows - when their is a a eureka or inspiration then that will force the popup / audio to work but next stops again next time its due to show

**Comment by sparrow8332** [comment]
best way to describe is with an image - [https://i.imgur.com/Qg64MlA.jpg](url)

**Comment by ricanuck** [comment]
Strange... can you start Firetuner while playing and see if lua errors come up...? I am seeing the popups normally, using the latest master...

**Comment by sparrow8332** [comment]
Just ran firetuner played 8 turns 4 times a civic/tech pop-up should have been displayed and on each time nothing. No lua errors being displayed either its been pickling my head all evening lol

**Comment by ricanuck** [comment]
I will try again to see if I just did not notice (hardly, but who knows...?)... did you try vanilla to see if it perhaps is one more Summer bug...? :roll_eyes:

**Comment by sparrow8332** [comment]
yea tried plain old boring vanilla :-) and they show fine. when i was playing around in my lunch break today with adding more off a visual notification to the inspiration boosts i broke the tech tree from opening but the pop ups appeared lol reverted back to the public version and they vanish again. im almost 90% sure its to do with techciviccompletedpopup.lua but im no where near as experienced as yourself so prob way off :-p

**Comment by sparrow8332** [comment]
In the beta branch the pop ups are showing just fine :-s this is a weird moment in my life lol  im lost to what the hell is going on hahaha

**Comment by ricanuck** [comment]
cleared cache?

**Comment by Azurency** [comment]
I had this bug a couple of time too. At first, I though I just kept missing the popups but if more people have the same problem, it's worth trying to understand where it comes from.

**Comment by ricanuck** [comment]
I tried for 30+ turns just now, and not a single problem with the popups... I doubt this is a bug, I cannot reproduce it.

**Comment by sparrow8332** [comment]
if not a bug gonna have to think about whats causing it then #facepalm lol its not just myself a few people have reported it to me as well as youtubers and twitch streamers so would like to see if we can get to the problem and fix if at all possible

**Comment by Azurency** [comment]
No that a bug, I just loaded a game and the popup appeared the first time and now it's not anymore, there's something

**Comment by Azurency** [comment]
Ok so it seems to be related to the `PopupPriority.Low` it's not properly dequeuing the popup :/
https://github.com/Azurency/CQUI_Community-Edition/blob/a2f1aa36d59b66394c1d0e252553fb78b7b17f64/Assets/UI/Popups/techciviccompletedpopup.lua#L35 When you change it to Normal or Current, it's working fine.

**Comment by sparrow8332** [comment]
i wonder if Boost popups priority can be set ....  i bet you its this bloody summer patch thats screwed something up as i cant see any reason why being in low priority would stop it showing altogether

**Comment by Azurency** [comment]
Maybe they touched the UIManager popup queue logic and now there's a bug with low priority, that's definitely related to that. 
When I set the priority to something below 100 and test (by completing research with live tuner) it's not showing the popup, but when the propriety is set to something over 100 it's working fine

**Comment by Azurency** [comment]
And yes, the tech boost priority can be set, so a quick fix would be to raise the boost priority and set the tech/civic priority to normal.

**Comment by ricanuck** [comment]
told ya, the bloody Summer "pat-shite"... :roll_eyes:

**Comment by therealcrow999** [comment]
Yeah I have same issue. I ticked on to have Visual as well as the Audio pop-up for Tech and Civics. When I started game, it works fine. Somewhere around 20 moves in it stopped. If I shut down game and start CiV6 again and load save, it will work for a few turns. Sometime the Civics will give me pop-up and audio, but the Tech stuff won't.

**Comment by Azurency** [comment]
So I tested today, and I also have the bug in vanilla... that's a shame. 
We'll fix this by raising the priority to _high_ for the boosts popup and _normal_ for the tech/civic. 
It's worth noting that tech/civic is the only popup that uses this `PopupPriority.Low`, we should revisit this next patch to see if it's fixed.
