### ISSUE TITLE
Diplo Banners optional: feature request

### ISSUE THREAD

**Issue by ricanuck** [Azurency/CQUI_Community-Edition#135]
One thing that drives me crazy since forever are those banners hanging from the leaderheads... do you all like them, or did you just get used to them? I remember that I coded the expanded tooltips for the leaderheads just because I could not convince Chao to get rid of the banners...

Anyways, I find myself outcommenting code and deleting diplomacyribbon.xml with every single new master I download, so I always wanted to make it optional (but Chao did not)... maybe now? What do you say? Do you really like those banners and the limited information, or do you prefer the highly flexible and expandable LH tooltip with much more info?

Let me know. I will assign this to myself for now.

**Comment by sparrow8332** [comment]
making the banners a toggle option in the settings but toggled ON as default would be a great idea 👍

**Comment by Azurency** [comment]
I like the diplo banners, I think it quickly gives an overview of different stats without having to hover each leader head and that's a great thing.
But adding a setting to toggle it would not cost much yes.
