### ISSUE TITLE
City State Base Mod fix update.

### ISSUE THREAD

**Issue by randomzebra** [Azurency/CQUI_Community-Edition#146]
Is it possible that you update the CQUI patch that fixed the issue with the trade screen not showing up for the latest version? The patch hasn't been updated since April 12th and appears to have stopped working.

**Comment by ashwinnr** [comment]
Having the same issue, fix would be appreciated. No trade screen since the patch today.

**Comment by randomzebra** [comment]
The coders are working to update the mod so that it will work with the current patch. This is a specific mod compatibility issue between the City States Basemod and CQUI.

**Comment by ashwinnr** [comment]
I don't have any other mod except CQUI-Comm
