### ISSUE TITLE
city banners no show and CIVICS TREE DOESNT OPEN

### ISSUE THREAD

**Issue by jimmyp1979** [Azurency/CQUI_Community-Edition#159]
placing a city , any city the banner of city name is a no show and more importantly the civics research does not EVEN open so you never progress, plus the bar at top showing science , faith etc constantly moves about , really?? is this a priority as no one can use this mod

**Comment by Azurency** [comment]
see #152

**Comment by cpinter** [comment]
Also, https://en.wikipedia.org/wiki/All_caps

**Comment by jimmyp1979** [comment]
wow thanks for helpful INPUT lol lol

**Comment by cpinter** [comment]
This is a friendly place, no need for "shouting". Thanks

**Comment by jimmyp1979** [comment]
wasnt shouting its to express a word louder,and therefore more important , read the wiki you sent  but again thank you
