### ISSUE TITLE
City menu and production menu sliding endlessly

### ISSUE THREAD

**Issue by Azurency** [Azurency/CQUI_Community-Edition#16]
I clearly have seen this issue multiple times now _(I can often reproduce this bug by double clicking on the city banner for exemple)_

**What it think it is**
It's seems to be related to the new city banner hovering, this line to be exact (when it's commented, I don't see the bug when clicking on the banner)
https://github.com/Azurency/CQUI_Community-Edition/blob/c4397b57859ab6ede93bd261dfd7e545ed0ed727/Assets/UI/WorldView/citybannermanager.lua#L273 So it seems to be related to the new ML citizen management, I'm looking into it.

We should also not exclude the fact that I tweaked the `CQUI_OnInterfaceModeChanged` of the `citypanel.lua` and it might have introduced a buggy behavior (but I don't think so, it's only when I click the banner that I see this endless sliding, when I click on the city itself on the map, it's working fine)

**Comment by Azurency** [comment]
From the steam workshop : 

> 3. Production Que - With the original CQUI, I could not get the production menu to remain open when clicking on a city from time to time and would have to wait until whatever was in my the que finished (all buildings/units) before I could choose new productions. This is particularly annoying when wanting to make any changes or purchase something. This problem still persists. However, it has also gotten worse. Now the city menu and production menu are sliding (opening and closing) endlessly. I am unable to close either out or go to the next turn.

**Comment by Azurency** [comment]
Actually, I may come from the `CQUI_OnCityviewDisabled` and `CQUI_OnCityviewEnabled` that set the interfaceMode back and forth endlessly via `CQUI_OnInterfaceModeChanged`

**Comment by Azurency** [comment]
I hope it's fix now, I haven't seen the bug with the changes made to `CQUI_OnInterfaceModeChanged`

**Comment by sparrow8332** [comment]
I havent had any issues mate and none reported on steam. Great job
