### ISSUE TITLE
Trade screen misalignment from time to time

### ISSUE THREAD

**Issue by Azurency** [Azurency/CQUI_Community-Edition#17]
The "My Offer" box is sometime not aligned correctly

![53c6981753b4db7b3a63b690af2f5ec23e1f7c83](https://user-images.githubusercontent.com/8012430/30420119-e5b15274-9938-11e7-957d-acbc0de26ee3.jpeg)

**Comment by Azurency** [comment]
I now do a `ReprocessAnchoring()` for the `CenterDealOffersStack` 
https://github.com/Azurency/CQUI_Community-Edition/blob/e9fa716bfd1d5693706eba68c762606f66e8cad0/Integrations/IDS/diplomacydealview.lua#L1298-L1310 Also the `MyOfferLabel` and `TheirOfferLabel` are sometime misaligned also so we should `ReprocessAnchoring()` for them also.

I think it fixed the misalignment (I could not reproduced the bug after the modification) but I'm not sure.

**Comment by BlackSmokeDMax** [comment]
This happened to me today. Is the fix not pushed to Steam build yet? Hopefully that is still the only issue with this! *crossesfingers*

**Comment by Azurency** [comment]
Yes it's not pushed to the steam build yet 😉

**Comment by sparrow8332** [comment]
will push the latest changes to steam later tonight when i get home from work :-)
