### ISSUE TITLE
Cant build districts or wonders

### ISSUE THREAD

**Issue by Ragnar157** [Azurency/CQUI_Community-Edition#176]
Hi,

i'm using the Github version of CQUI on Civ6 .194.
i tried 2 games and cant build any districts (only researched encampment and campus) and also a wonder that was available to me.
i can select it from the list and the screen goes into tile selection mode where i see eligible tiles, but then when i left-click them nothing happens.
More Info: no other Mods loaded, Windowed mode & Fullscreen, Win10

**Comment by cpinter** [comment]
As I learned recently, a few things to use the latest:
* Make sure you use the fall-2017 branch
* Remove this postfix from the name of the directory once unzipped (not sure if this needed)
* Unsubscribe from the CQUI mod on steam (this is what I missed)
Then it should work, as this was fixed.

That said, the mod in steam workshop will be updated very soon now.

**Comment by oerms** [comment]
@Ragnar157 @cpinter 
The Steam version has been updated about an hour ago and all should be working now without any fuzz.
Be careful not to try and run two versions (git and steam) at the same time.

**Comment by Ragnar157** [comment]
im not familiar with github so i didnt have the fall-2017 branch.
solved thanks!
and thanks for the great work, i wouldn't wanna miss CQUI anymore!
