### ISSUE TITLE
Latest update broke my game

### ISSUE THREAD

**Issue by the47thman** [Azurency/CQUI_Community-Edition#177]
This afternoon's patch downloaded for me before I started playing. Unfortunately, when I got into my previously-saved game, things weren't working-- the lower right icon was spinning on the "Please Wait" stage, as though I was between turns, and the only thing I could do was move units-- but not take actions, as the action bars didn't pop up.

Looking at the patch notes, I'd guess that this is related to the fact that the update was related to the Fall 2017 patch, and I'm on Mac, which hasn't yet received said patch. Time to root around and see if I can revert the patch...

**Comment by oerms** [comment]
Unsubscribe from steam, download [this zip](https://github.com/Azurency/CQUI_Community-Edition/archive/03568ab7793eae124c4b244b3da1f474b8b4e368.zip) and install as describes for Mac. This should revert CQUI to before the Fall-2017 patching began.

**Comment by the47thman** [comment]
That seems to have done the trick. Thanks!

**Comment by vttale** [comment]
How super sad that I discovered this only at the start of 17.5 hour flight.... argh.

**Comment by Pauloel7** [comment]
Please, can someone explain how to install the Fall 2017 version (mac)? I do not get it. If I unsubscribe here on steam the mod does not run at all. I did dowload the Fall 2017 files, and did drag them into the folder /Users/[user]/Library/Application Support/Sid Meier's Civilization VI, but it does not run on its own, nor can I activate it in-game, with that "Additional Content" buttom. Help!
