### ISSUE TITLE
Relationship tooltips not displaying with new code

### ISSUE THREAD

**Issue by ricanuck** [Azurency/CQUI_Community-Edition#179]
As I mentioned in the PR I uploaded, the relationship tooltips are not displaying consistently when hovering over the Relation icons underneath the leader icons in the diplo ribbon. I have tested multiple times, new games and ongoing, and just now with the recently released Fall update.
The old code that was there before the Summer patch, calling the instance of the leader icon object, works fine.
I am aware that some are not able to reproduce, but I am. I encourage you to merge the PR so that we can ensure that the relationship tooltip, a very useful diplo tool, works as intended.

**Comment by Azurency** [comment]
And what happens when you call updateIcon of leaderIcon, manually from the console ?

**Comment by ricanuck** [comment]
Didn't try yet. The point still is, when an inconsistency like this appears, we have to assume it is appearing in many cases out there, even if people do not report it (or even if many people are not using the feature, which I doubt as it is a very cool and useful feature). The spirit in CQUI was always to provide a consistent, better experience with the mod, and only after that to try and investigate issues like this to find a better, final solution.
From my experience with modding Civ 6 (and previous versions), a lot of this type of inconsistent behavior is rooted in FXS "coding practices"... we can either waste a huge amount of time trying to do their job for them, or we can try and compensate for their faults using known working code. In this case, the old code for this feature is still proving to work perfectly, that's why I uploaded this PR... just merge it, so we make sure the feature works across the board, and then, if we have time to spare, we can investigate where the inconsistency originates (and my bet is, once, again, within the black box of FXS code, aka the dll).

**Comment by Oscar-IronTower** [comment]
I can confirm it happens to me as well. Came here to report it. When hovering over the relationship icon on the main screen I only get the name of the status (friendly, for example).

**Comment by ricanuck** [comment]
@Azurency : even if only a few of us are reporting, it is enough to assume that the problem is out there. Given that the solution is already pushed and waiting a merge, and that said solution does not affect anything else and does not break the feature (quite the opposite, it saves it), I cannot understand why the PR has not been merged yet.

**Comment by Azurency** [comment]
I though you would give me more inputs to try to figure out what happened... or at least try what I told you to try but anyway, I'll merge your old code
