### ISSUE TITLE
I think the Production Chooser fails to show entirely in Scenarios

### ISSUE THREAD

**Issue by alanhogan** [Azurency/CQUI_Community-Edition#18]
In the Nile and in Alexander scenarios (the two I tried), I cannot get the Production pane to come up when looking at a city.

It seems to work for normal games however.

I'm on macOS. I didn't have any other mods running, just this one.

<img width="338" alt="screen shot 2017-09-16 at 4 17 00 pm" src="https://user-images.githubusercontent.com/6808/30516677-805a47aa-9afa-11e7-9ac4-aa3464e9c508.png">

**Comment by Azurency** [comment]
It's a known issue from the original CQUI `Most scenarios don't work with CQUI` https://github.com/CQUI-Org/cqui/issues/186
