### ISSUE TITLE
[Request] Number of civics for AI players visible in toop tip

### ISSUE THREAD

**Issue by skodkim** [Azurency/CQUI_Community-Edition#180]
Would it be possible to add the number of civics an AI player has unlocked in the leader head tool tip on the upper right side of the screen - just like it works with number of techs researched?

\Skodkim

**Comment by oerms** [comment]
Hi @skodkim 
Unfortunately this seems not to be easily done.
In contrast to the number of techs researched – which the game calculates by the function `GetNumTechsResearched()` – there is no such function for the number of civics. The function for the techs is hard-coded in `GameCore_Base_FinalRelease.dll`.

Others: Please correct me, if I am wrong.

**Comment by Azurency** [comment]
No I think it can be done. Something like this should work, for each AI player : 

```lua
local civicsCount = 0;
local playerCulture = Players[TheIfOfThePlayer]:GetCulture()
for row in GameInfo.Civics() do 
  if playerCulture:HasCivic(row.Index) then
    civicsCount = civicsCount + 1
  end
end
```

**Comment by oerms** [comment]
Ah, I see. Didn't know, all civics could be traversed as easily. If it's ok, I will try and implement this in the coming days.

**Comment by ricanuck** [comment]
Loops can solve almost anything, but as a coder, gosh I hate to abuse loops... they are an infinite source of performance trouble.
With that said, the idea of the leaderhead tooltips (when I created them) was to replace the (to me) horrible diplo ribbon banner. With that purpose, what I wanted was basically a flexible info display.
In other words, we can add whatever we want to that tooltip, as long as that info can be found in some way in vanilla (CQUI being a non-gameplay-altering mod ala BUG mod for civ4).

**Comment by Azurency** [comment]
Yes, you're right, I though we had this information in vanilla but it's not here. So we should not add it to CQUI.

**Comment by oerms** [comment]
I would like to add the era, this allows to judge the capabilities of each other player more easily. Especially when loading a game after some time.
Cross referencing the little icons in the tree with the army values and points should be done automatically.

**Comment by oerms** [comment]
Btw, I agree that we should not add info that is not there already somewhere in the game.

**Comment by skodkim** [comment]
Don't add anything that your uncomfortable with. 

It's just that I've always wondered why number of techs was visible while number of civics wasn't.

**Comment by ricanuck** [comment]
@skodkim : it seems to be a design decision... maybe because the Civic Tree has many more leafs than the Tech tree? Meaning that in the case of the Civic Tree, Era is much more telling than number of civics.
Or, surprise again, FXS messed up their code... either way, if it's not in vanilla, CQUI does not add it (the "cheating" argument).

**Comment by skodkim** [comment]
That's fine, I'll just close the issue then. I wasn't even aware of your 'cheating' policy when I requested it :-)
