### ISSUE TITLE
I can see other Civs' Spies

### ISSUE THREAD

**Issue by Jman5** [Azurency/CQUI_Community-Edition#187]
I noticed I can sometimes see deployed Spies. It seems intermittent, and I'm not sure what triggers it, but it's not some visual mistake. For example, earlier I saw an Aztecs spy in my Commercial district and shortly after they stole money from it. I'm using the latest version, but I was using an earlier version when I started it the other day.

https://i.imgur.com/wc4HVZb.jpg

Mods: 8 ages of pace, Smoother Difficulty, Start position Hotfix

**Comment by datbunneh** [comment]
Actually can confirm. Not using any mods except this one.

**Comment by Jman5** [comment]
Also I think this is related, but I just saw someone else's Privateer pop up on my map out of no where and on the other side of the world. I don't even have caravels, and I don't think its a city state's. It actually revealed a natural wonder for me oddly enough.

**Comment by ricanuck** [comment]
Yes, I can confirm, but I am not sure  it is CQUI, as this game is the first I finished since the Summer fiasco. Can anyone test vanilla and see if it happens there too? I suspect Firaxis changed how spies work, maybe? I noticed it only happened when I got the big bonus to domestic spies from cards and promotions.

**Comment by ricanuck** [comment]
OK, just tried, vanilla does not have this bug. This is high priority, as it becomes cheating.

**Comment by BeppyDawn** [comment]
I've also experienced this bug. Oddly enough I also saw Aztec spies in my Commercial district.

**Comment by roberto-ii** [comment]
It seems when a supposed-to-be invisible unit moves near your borders or near an allied unit it becomes visible and stays visible unit you exit the game. I saved a game where enemy privateers and spies were visible, exited to the main menu, then opened the save and all the units were invisible. But once i did a next turn, the privateer showed up again when it moved. I don't recall if the spies reappeared.

**Comment by ricanuck** [comment]
@roberto-ii : can you try vanilla only to see if it happens there too?

**Comment by roberto-ii** [comment]
I'm not running  a completely vanilla game (there are a few other relatively benign mods) - but the problem occurs only when CQUI is running. When I disable it, invisible enemy units stay invisible

**Comment by AkshaySrivatsa03** [comment]
I experienced this problem as well. Was playing as Japan and had allied with Rome, when I suddenly saw their spy in my capital. I distinctly remember seeing their spy enter my capital itself (City Centre district) and then move into my campus district. I was able to construct a spy and capture the Roman spy.
I am using the latest CQUI mod and no other mods.

**Comment by Timmeey86** [comment]
I've created a workaround in #197 which will at least prevent enemy spies from being visible. The real issue is maybe somewhere else, though.

**Comment by Azurency** [comment]
That was my mistake sorry, I assumed the `Refresh` function was already used in the vanilla game but it was not (or only for dev. purposes with hot reloading), it showed all units (even hidden ones) when it was called. It's fixed now.
