### ISSUE TITLE
Government Policy screen is gone

### ISSUE THREAD

**Issue by Calonius** [Azurency/CQUI_Community-Edition#188]
Playing on my mac, there's a major gamebreakinig bug, which is that I'm unable to open my government policy screen. I click on the icon and nothing happens. 

Also there's a couple of minor bugs. The alert feed on the right hand side of the screen is not displayed properly, it's just a long string of generic "alert" icons with not text or functions. And the path viewer for units shows that units that aren't moving have a path that just goes off screen. But it's purely cosmetics as the units don't actually take this path.

**Comment by oerms** [comment]
Another MAC user reported issues in #177. Please have a look there if this solves it for you.
