### ISSUE TITLE
[Request] Compatibility with JFD's Rule With Faith

### ISSUE THREAD

**Issue by skodkim** [Azurency/CQUI_Community-Edition#189]
Would it be possible to make CQUI compatible with JFD's Rule With Faith again (there used to be a CQUI RWF version on Steam)?

There's some issues in the civics tree and government screen as RWF adds cultural and religious civics class. Furthermore RWF adds a Great Theologian unit which messes up the Great Person screen.

So far is seems I've come around the issues by removing the files beneath from CQUI, but it'd be great if you could make it truly compatible . Your screens are far superior!

\Assets\UI\Screens\civicstree.lua
\Assets\UI\Screens\governmentscreen.lua
\Assets\UI\Screens\governmentscreen.xml
\Assets\UI\techandcivicsupport.lua
\Assets\UI\Popups\greatpeoplepopup.lua
\Assets\UI\Popups\greatpeoplepopup.xml

\Skodkim

**Comment by ricanuck** [comment]
CQUI is the BUG mod for cvi 6. It is an Unaltered Gameplay UI mod. To preserve that spirit, it should never integrate any gameplay-altering modifications or cheats. I will oppose such possibilities to death.

**Comment by skodkim** [comment]
Ehhh, I'm not suggesting that you incorporate it - just make or compatible (as you did up until recently).

\Skodkim

**Comment by thecrafybee** [comment]
I would love to see compatibility with RWF too.

**Comment by skodkim** [comment]
@thecrafybee

For now just remove the above mentioned files and it should work ok (but not as flashy as cqui).

\Skodkim

**Comment by Azurency** [comment]
Same as #118 . I'll just quote what chaorace said, because I have the point of view:

> That being said, I'm not against the idea of making CQUI more compatible with other mods, especially those which can't be integrated into CQUI for whatever reason (in this case, since it's non-vanilla gameplay).

But it's definitely not a priority for now.

**Comment by skodkim** [comment]
@Azurency That's fine, I understand that you've got other priorities and we can actually play with CQUI+RWF if we just use a few tweaks. I was just making a request (partly because there had been a released version before). Also I just didn't understand the "melodramatic" comment about "opposing such possibilities to death" given that I consider it a valid/innocent request (and I apologize for the phrasing, English is not my native tongue and I can't really find a better way to say it).

\Skodkim

**Comment by Azurency** [comment]
@skodkim yes I didn't understand it either and I'm really sorry. It was an innocent request and his answer was not really appropriate

**Comment by Azurency** [comment]
I'll close this since there's already another issue with that subject
