### ISSUE TITLE
UI disappears

### ISSUE THREAD

**Issue by 8h42** [Azurency/CQUI_Community-Edition#19]
Screenshot:
![ss](https://user-images.githubusercontent.com/11933188/30691700-8faf2ee8-9f03-11e7-8a29-4937cddd98c1.png)

Active mod:

- Community Quick User Interface - CQUI (2017.09.21)

Save file:
[00001-test.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1320827/00001-test.zip)

Log file:
[Logs.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1320828/Logs.zip)

Note that I play Civ6 in Japanese.
Interestingly, I can't reproduce this issue when I switch the language.

Similar report?
Civ 6 UI Disappears while loading turn Modded [1.0.0.167]
http://forums.civfanatics.com/threads/civ-6-ui-disappears-while-loading-turn-modded-1-0-0-167.622472/

**Comment by 8h42** [comment]
I resolved this problem by deleting these lines.

https://github.com/Azurency/CQUI_Community-Edition/blob/ff4533853f1270fcfdf0469102426903496b997e/Assets/UI/diplomacyactionview.lua#L1243-L1246

Is this code necessary?

**Comment by Azurency** [comment]
The problem come from `LOC_GOSSIP_SOURCE_DELEGATE` not being defined (or not finishing by a word). It's odd because it came from the old gossip integration but I fixed it. Can you send a zip of the current mod you're using ?

**Comment by 8h42** [comment]
Only the latest CQUI (Steam Workshop version).
[1125169247.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1321408/1125169247.zip)
I also tried the CQUI_Community-Edition-master, but the same issue occurred.

**Comment by 8h42** [comment]
I checked the Vanilla_ja_JP.xml.
Some gossip texts (including `LOC_GOSSIP_SOURCE_DELEGATE`) put a **Colon** at the end of their sentences.

![text](https://user-images.githubusercontent.com/11933188/30701026-3d5dcfde-9f24-11e7-9e5f-a3c5dbae5477.png)


Is that what caused this error?

**Comment by Azurency** [comment]
Yes it should be the issue, the pattern is looking for a word at the end of the sentence, I'll look at it later today.

**Comment by Azurency** [comment]
Ok so the bug came from the fact that there is no spaces in the Japanese sentence, it will be fixed in the next release

**Comment by cpinter** [comment]
I'm having the same issue with the latest community mod in the workshop. Four games, two computers, same thing. It happens after hitting next turn, once the AI finished their turns and mine would start. Any ideas? Thanks!

**Comment by cpinter** [comment]
Update: I finally uninstalled and re-installed the game, and now I'm in turn 157 and the issue hasn't occurred, although it happened always by turn 50. It seems the problem was not related to the mod.
