### ISSUE TITLE
City attack glitches

### ISSUE THREAD

**Issue by georgwacker** [Azurency/CQUI_Community-Edition#192]
- City info popup has overflowing xp bar 
- City attack button recenters the camera to the city, making it impossible on some instances to target units behind the city info bar (because you cannot move the camera to see the unit, and then attack)

![city_attack_glitch](https://user-images.githubusercontent.com/13589801/32446724-10c84fa8-c30a-11e7-9821-64ea7b8d05ae.PNG)

**Comment by ricanuck** [comment]
Glitches are vanilla. Thank Firaxis.

**Comment by georgwacker** [comment]
#196

**Comment by Azurency** [comment]
I fixed the xp bar (and some unit flag hover bug also). 
Also when in city range attack mod you can move you camera freely to target the unit you want easily.

**Comment by georgwacker** [comment]
Please look at my pull request. I fixed the xp bar by just checking for a divide zero, which is more universal.

Right now, it recenters the camera every time you click on the attack button, which can be quite tedious in some situations where you want to reposition the view. My pull request only centers on the city when clicking on the action or notification panel.

**Comment by Azurency** [comment]
I've seen your pull request. The XP bar is already fixed by checking the interface mode. Your change is also a valid option, but with the interface mode, we understand better why we did that and maybe remove it if firaxis fix it in the future.

Yes, clicking the button recenter the camera, but you just need to click it once, and then move the camera with your pointer. I don't see why it's tedious ?

**Comment by georgwacker** [comment]
Good point on understanding the change later on.

I think I meant to say irritating instead of tedious. I had a game situation where I had multiple targets to attack from the city and they were positioned behind a large city bar. I also had a bunch of other units near the city. So I would enter city attack mode to see which units I could target and switch back and forth (exit attack mode) to plan my move. Because of the positioning of the enemy units behind the city, I would move the camera up each time, just to get it snapped back by the attack button. 
It's a small quality of life change, but I had a couple of instances where the current recenter annoyed me.

Perhaps I could make it optional?
