### ISSUE TITLE
Minimap resizes to vanilla setting on entering game options

### ISSUE THREAD

**Issue by georgwacker** [Azurency/CQUI_Community-Edition#193]
This happens when the vanilla minimap size (under interface) is set to minimal and the default CQGUI minimap size is set to 512. On entering game options the map is resized to the vanilla value.

![minimap_glitch](https://user-images.githubusercontent.com/13589801/32447420-55a99904-c30c-11e7-9dee-17aee8b48055.PNG)

**Comment by Azurency** [comment]
We'll look at this bug, a quick workaround is to not set the size of the minimap with the vanilla settings but instead only in CQUI.
