### ISSUE TITLE
World Tracker minimize panels not functioning

### ISSUE THREAD

**Issue by hclyatt** [Azurency/CQUI_Community-Edition#194]
In the vanilla Civ IV UI there is a selection button on the top right side of the world tracker that will minimize all the world tracker panels when it's clicked. Essentially this is the same as unchecking both the Research and Civil panels in the world tracker.  In CQUI this selection button does not work as intended. When you click on it the panels won't minimize but instead graphical artifacts will display just to the right of the world tracker itself. Please see the attached images for reference.

![sid meier s civilization vi dx11 11_5_2017 9_30_38 pm](https://user-images.githubusercontent.com/33439418/32473996-41148126-c338-11e7-9376-a1cef1110066.png)
![sid meier s civilization vi dx11 11_5_2017 9_30_55 pm](https://user-images.githubusercontent.com/33439418/32473997-4120be28-c338-11e7-908a-386fcad6d346.png)
![sid meier s civilization vi dx11 11_5_2017 9_31_17 pm](https://user-images.githubusercontent.com/33439418/32473998-4132f6ec-c338-11e7-8ddb-1ce3382422c6.png)
![sid meier s civilization vi dx11 11_5_2017 9_31_35 pm](https://user-images.githubusercontent.com/33439418/32473999-414170a0-c338-11e7-9f5b-f584070b0f06.png)

**Comment by sparrow8332** [comment]
already discussed in #14
