### ISSUE TITLE
Modular Screens

### ISSUE THREAD

**Issue by EwokBaconBits** [Azurency/CQUI_Community-Edition#198]
I am the maker of the military doctrine mod. I recommend the CQUI mod for modular compatibility with my mod so people have a button in the launch bar, otherwise they have to use a hotkey. I'm not sure this has come up before but it seems that since I believe the last patch for CQUI the modularity isn't working. Another version that I have of CQUI from Oct 22nd is working and it did work with the last game patch. 

Has something changed since then or is this a problem that has not been addressed?

Thanks in advance!

**Comment by EwokBaconBits** [comment]
It looks like other issues have been brought up about the world tracker so perhaps these are connected to the Modular Screens mod.

**Comment by Azurency** [comment]
Do you mean that `LuaEvents.LaunchBar_AddExtra()` is not working ? You don't have any errors in the logs ?

**Comment by EwokBaconBits** [comment]
This is what I had before (taken from an example sukritact had), I noticed that the references were commented out in the launchbar for cqui - was this something causing problems with the latest patch?

I am not getting any log errors.

`local sTooltip = Locale.Lookup("Doctrines[NEWLINE][NEWLINE]View and choose your military doctrines.")

local tButton = {
	InstanceType = "LaunchBarItem",
	SelectFunc = function() LuaEvents.DoctrineOpenManager() end,
	IconTexture = "LaunchBar_Hook_Doctrine.dds",
	Tooltip = "Doctrines[NEWLINE][NEWLINE]View and choose your military doctrines."
}

table.insert(g_TrackedItems, tButton)

-- ===========================================================================
-- Just in case we need to make changes to the button
-- We can grab the instance from the global table via the unique tooltip!
-- ===========================================================================
local DoctrineInstance

function Doctrine_OnLoadScreenClose()
	for i,v in ipairs(g_TrackedInstances) do
		if v.LaunchItemButton:GetToolTipString() == sTooltip then
			v.LaunchItemButton:SetTexture("LaunchBar_Hook_DoctrineButton.dds")
			DoctrineInstance = v
			break
		end
	end
end
Events.LoadScreenClose.Add(Doctrine_OnLoadScreenClose)`

I tried to implement it through the examples shown for Modular Screens but this did not work either, though this I cannot confirm was working before so maybe I missed something in this code.

`function Doctrine_OnLoadScreenClose()
	PRINT('LOADING DOCTRINE BUTTON');
	textureOffsetX, textureOffsetY, textureSheet = IconManager:FindIconAtlas("ICON_UNIT_JAPANESE_SAMURAI", 38);
	  local button2Info = {
		-- ICON TEXTURE
		IconTexture = {
		  OffsetX = textureOffsetX;
		  OffsetY = textureOffsetY+3;
		  Sheet = textureSheet;
		  Color = UI.GetColorValue("COLOR_PLAYER_BARBARIAN_PRIMARY");
		};

		-- BASE TEXTURE (Treat it as Button Texture)
		BaseTexture = {
		  OffsetX = 0;
		  OffsetY = 0;
		  Sheet = "LaunchBar_Hook_Doctrine";
		  -- Color = UI.GetColorValue("COLOR_BLUE");
		  HoverOffsetX = 0;
		  HoverOffsetY = 0;
		};

		-- BUTTON INFO
		Callback = function() LuaEvents.DoctrineOpenManager() end;
		Tooltip = "Doctrines[NEWLINE][NEWLINE]View and choose your military doctrines.";
	  }

	 LuaEvents.LaunchBar_AddIcon(button2Info);
 end
  
  
function Initialize()
	Events.LoadScreenClose.Add(Doctrine_OnLoadScreenClose);
end
Initialize();`

**Comment by EwokBaconBits** [comment]
Ok I have figured this out, I just placed onloadscreen into my doctrine UI panel instead of seperate and it works. Thanks

**Comment by Azurency** [comment]
Glad that you figured it out ! 👍
