### ISSUE TITLE
Accidental Tile Purchases

### ISSUE THREAD

**Issue by sparrow8332** [Azurency/CQUI_Community-Edition#201]
As stated by mlahor on steam:

Hello, does anybody have a problem with accidental tile purchases happening far too often? It happens to me all the time, and it happened to Quill on the stream too.
It is far too easy to accidentally click the purchasing part of the tile when dragging the map around in the city view. I think it would be easy to fix this for example by requiring a double-click when purchasing tile or something of that nature. How does everyone feel about it?

**Comment by cpinter** [comment]
Agreed, it happens 2-3 times every game. Then I either have to live with the loss of ~100 gold, or lose my "no-load badge" if it happens at a critical time.

Not sure though if double-click is the best solution, as it can be non-intuitive, causing confusion for some people. My suggestion would be to only buy the tile on mouse release AND only if mouse press and release happened at the exact place (no drag&drop). It may be just me but it mainly happens when I want to scroll (via drag&drop), so it would be a sufficient fix in this case, and would cause no confusion.

**Comment by BlackSmokeDMax** [comment]
I do it little enough that a confirmation window would be fine as well. 

Really anything is better than those accidental purchases, and never a tile you'd consider purchasing on purpose!

If cpinter's idea works, that may be acceptable, I'd certainly be willing to try that method first.

**Comment by sparrow8332** [comment]
maybe able to do something with m_isMouseDragging and m_hasMouseDragged ?   will need a proper look into it

**Comment by datbunneh** [comment]
I support @cpinter way of solving it. The tile purchase should not trigger after you started dragging.
If you simply introduce confirmation window (which can be done as additional measure but not primary) people will still get annoyed to have to press "No" on the regular basis.

**Comment by sparrow8332** [comment]
#208

**Comment by cpinter** [comment]
@sparrow8332 Well, it has a high gain/effort ratio for sure :) It's probably worth merging if there is no better solution. I'll take a quick look and try to figure out how much harder would it be to implement what I proposed.

**Comment by cpinter** [comment]
Maybe a noob question but if I register multiple callbacks on the same object, why only the last one seems to be connected? I have three callbacks on the button, and depending on the order the first two is never called, but the last one is. Any ideas?

**Comment by cpinter** [comment]
OK I think I give up.
1. It seems that only a very limited number of mouse events can be registered to an object together, and what I'd need to determine dragging cannot (like LButtonDown, LButtonUp, MouseMove)
2. SetInputHandler only works for the main context, not for any object (like PurchaseButton), and I don't know how to hack this logic into the main OnInputHandler (need to get purchase button object somehow)

If anyone has any ideas I'm happy to share what I have so far.

**Comment by sparrow8332** [comment]
thats the issue i was having thats why i settled for the simple but effective option off right click :-)
