### ISSUE TITLE
Improved Resource Icons Are Always Transparent On Game Load

### ISSUE THREAD

**Issue by datbunneh** [Azurency/CQUI_Community-Edition#206]
**Expected Behavior:**
Improved resource icons' opacity is set according to corresponding option on game load.

**Current Behavior:**
Improved resource icons are always transparent on game load.

**Steps To Reproduce:**
1. In CQUI options choose to display improved resource icons as solid.
2. Improve some luxury/strategic/bonus resources.
3. Save the game.
4. Load the game.
5. Note that option is actually saved properly but the icons are transparent until it's reapplied.

**Comment by Azurency** [comment]
Indeed, there was a missing event in the `worldviewiconmanager.lua`. I fixed it. It should be ok in the next version on steam or next time I'll push on GitHub.
