### ISSUE TITLE
Religion Tab of City Panel showing incorrect info (or not updating)

### ISSUE THREAD

**Issue by RandomOfAmber** [Azurency/CQUI_Community-Edition#209]
Hi there, 

I'm using the latest master build of CQUI CE (direct download from here rather than Steam Workshop version) and I am experiencing a strange bug in my current game. The city panels of all my cities (including my Holy City: [https://www.dropbox.com/s/pnkdphi12vl19h8/289070_20171109231716_1.png?dl=0](url) ) are showing no information concerning my majority religion. Either the religion tab isn't updating at all, or something screwy is going on. E.g., in the screenshot I've linked there, that city is the Holy City of Islam and, as the religion overview shows, it currently has 16/19 Islamic Citizens, yet the city panel shows nothing concerning Islam or its beliefs.

I don't THINK this is a mod conflict (I can't imagine how, since none of my other mods change any of the city panel files, or any of the same files as CQUI), but just in case, these are the other mods I'm playing with (and all the latest versions thereof):
[+ indicates installation via Steam Workshop]

+ Better Civilization Icons
+ Better Coastal Cities & Water Tiles
+ CIVIG (Civi Graphs)
+ Historicity ++
+ Immersive Dialogue
+ Kinetikam
Smoother Difficulty 1.4
+ Sukritact's Fuji
+ Sukritact's Policy Manager
+ Sukritact's Resources
+ Sukritact's Tonle Sap
+ Unique District Icons

If I can provide any further info, please let me know!  Thanks for your hard (and great) work on CQUI!

**Comment by Azurency** [comment]
I'll try to reproduce this, but that'll be nice if you could send the save of this game (so that we can test it easily)

**Comment by RandomOfAmber** [comment]
Forgive me! I (foolishly) didn't even think to do append my save file when I wrote my original post. The most recent (still showing the problems I've outlined) is available here:

https://www.dropbox.com/s/cgu5x8d4k3j7pio/GITARJA%20336%201575%20AD.Civ6Save?dl=0

Thanks again, and let me know if I can do anything else to help.
