### ISSUE TITLE
Required to use City Attack.

### ISSUE THREAD

**Issue by BlackSmokeDMax** [Azurency/CQUI_Community-Edition#21]
Playing 3 or 4 days ago and the game wouldn't let my turn progress without using the city ranged attack. Which I didn't want to use as I wanted to get some exp for one of units the following turns and there was no where for the enemy unit to escape or pillage.

Didn't right clicking on the Big Button used to end your turn no matter at one point? (may be thinking of a different game too!)

**Comment by Azurency** [comment]
I will look at it later this week.

**Comment by Azurency** [comment]
The summer patch in fact removed the skipping behavior of the right click. It'll be added back in the next release of the mod 👍
