### ISSUE TITLE
W overlaps keybind with WASD movement

### ISSUE THREAD

**Issue by quixadhal** [Azurency/CQUI_Community-Edition#210]
Hey, one little bug that many might not see.  I have edge-panning disabled because I run in windowed fullscreen mode with two monitors, and the game doesn't register the edge that joins the monitors properly.  So, I'm used to panning the display with WASD.  The W key with CQUI appears to open the "wonders" display on the key-up event, but still scrolls with the key-down event.

I can't find anywhere to change the keybinds to avoid the conflict, so I figured I'd mention it here.  Of course, I can use the arrow keys, it's just not as convenient.  Thanks for all the hard work!

**Comment by NoShotz** [comment]
You need to go into the games keybinding settings.

**Comment by quixadhal** [comment]
Of course, as I mentioned, I tried that and couldn’t find *anything* related to either setting.  Maybe it’s not obvious and is called something entirely unlike the screen it brings up?

Sent from Mail for Windows 10

**Comment by quixadhal** [comment]
Huh, I have no idea why I couldn't find it the other day... nevermind. :)

It might be nice to rebind the W and E default actions to something like shift-W or alt-W and E, but today my eyes see the place in normal settings to unbind things.  Sorry!
