### ISSUE TITLE
Intel report tab show nothing if the game language is Simplified Chinese

### ISSUE THREAD

**Issue by sunshulian** [Azurency/CQUI_Community-Edition#211]
Hello,my game language is Simplified Chinese, the Inter Report : Gossip page show nothing. Whatever I change the language to English or start the game without CQUI,there is no problem in  Inter Report : Gossip page.
![2](https://user-images.githubusercontent.com/33571742/32689348-cd29e410-c71d-11e7-9976-777d23fb9b22.PNG)
![1](https://user-images.githubusercontent.com/33571742/32689379-75fabe2a-c71e-11e7-9216-1e4a9e3dd0d6.PNG)

**Comment by Azurency** [comment]
There's indeed a bug here, I'll work on it

**Comment by Azurency** [comment]
Should be solved in the next update on steam 👍
