### ISSUE TITLE
[bug] City Info / Production Screen not working/opening

### ISSUE THREAD

**Issue by TheOmega010** [Azurency/CQUI_Community-Edition#214]
When you click on a city to open the info and production screen, it highlights the city but no items or information shows up. The production screen will show up if there it nothing being produced and you click on the turn button gear icon.

**Comment by Azurency** [comment]
Do you use other mods? Are you on Windows/Mac OS/Linux?

**Comment by U2328** [comment]
I've stumbled upon this bug as well, for my setup I'm running on Windows 10 (the direct x12 version of the game) and I'm running other mods as well, though I just went through and tripple checked that I don't have any other UI mods in there.
As for some of the mods:
* R.E.D. (with all the civ/dlc addons)
* MOAR units (with all the "Even MOAR units! packs)
* all conceivable compatibility mods and "combo mods"
* and some other game play altering mods, i.e. AI and unit/tile improvement mods

**Comment by Azurency** [comment]
@U2328 It's likely a mod conflict. In the logs, you have an error in `G:\Games\Steam\steamapps\workshop\content\289070\904443457\CityPanel.lua:1114` but CQUI have `citypanel.lua` in a `panels` so this error is not from CQUI and you also have a conflict because this other mod is changing the `citypanel` file.

**Comment by U2328** [comment]
I'll take a look, and see what I can find.

**Comment by U2328** [comment]
@Azurency So it does seem to be a different mod causing this, I'm now on the hunt which one it is. I'll right it in here when I'm done so you have this Info as well.

**Comment by TheOmega010** [comment]
You are correct that it was a different mod. The mod in question for me was the "Happiness Level - Euphoric" mod and was easily fixed.

**Comment by Azurency** [comment]
Great, so I'll close this issue then 👍
