### ISSUE TITLE
Peace deals are bugged

### ISSUE THREAD

**Issue by Senkichi** [Azurency/CQUI_Community-Edition#215]
When an AI offers you a peace deal (in my case it was Tomyris, for specificity) the screen is completely blank for both parties. Further, when proposing a peace deal the potential resources the AI has to offer don't show up, meaning theres no way to negotiate for them to cede one of their cities or give up other resources.

**Comment by Azurency** [comment]
Are you on windows/Mac OS/Linux ? Are you using any other mods ?

**Comment by ricanuck** [comment]
Smells like mod conflict. OP, detail mod list please.

**Comment by Faldryn** [comment]
I ran into this issue as well, but it only happens when playing as Persia and I take a city.

Windows
Other mods: YNAMP, Halved Warmonger Penalties, Smoother Difficulty.

**Comment by Senkichi** [comment]
I am using this mod exclusively, on Windows. I was also playing Persia, and to my recollection I took the city with an Immortal.

**Comment by ricanuck** [comment]
hmmm... Persia --> No occupation penalties --> Cede city functionality ??? Maybe starting around that...

**Comment by Faldryn** [comment]
With CQUI disabled, the peace deals function normally again.

**Comment by Azurency** [comment]
Can you please upload your save game it would be very useful for us to reproduce the bug.

**Comment by starkcolin** [comment]
Same issue, playing with Persia. Hope this helps.

[CYRUS 98 450 BC.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1500505/CYRUS.98.450.BC.zip)

**Comment by Gyomb** [comment]
I reproduced this issue with Persia as well. I noticed it happens only when you conquered one of the IA's cities. If you conquered none, the dialog displays normally.
Also, if you conquered a city during a first war, made peace without negotiating anything (because you can't), then started a new war and try peace again before you conquer any new city, the dialog is still empty.

**Comment by OmnipotentStomper** [comment]
Here's a save exhibiting this problem.
Try making peace with Teddy.
CQUI is the only mod in use.
(All DLC enabled as well.)

[CYRUS 156 900 AD.Civ6Save.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1509698/CYRUS.156.900.AD.Civ6Save.zip)
