### ISSUE TITLE
is it possible to change coloring scheme for the game? too much noise

### ISSUE THREAD

**Issue by alexeyOnGitHub** [Azurency/CQUI_Community-Edition#218]
it is hard to see what is going on on the map in the late game, where all enhancements are done.
I can hardly see my sleeping units in the background.
is it possible to change the coloring scheme so that nature and improvements are less bright, while units have more visibility? at least during a war.

**Comment by Azurency** [comment]
I think changing the color scheme would be too complicated and change the game too much for what it could bring to the player. I prefer to keep the default color scheme.

**Comment by oerms** [comment]
You might get an easier view of what is going on when deactivating the dynamic daytime and select a fix daytime where there are less colors like morning or evening.
