### ISSUE TITLE
Worker Lense Improvements

### ISSUE THREAD

**Issue by datbunneh** [Azurency/CQUI_Community-Edition#219]
1. Do not highlight tiles which are not in any city working range (3 tiles) except those containing luxury or strategic resources.
2. Highlight tiles with wrong improvements for strategic resources. Happens when tile was improved before the strategic resource was visible.

**Comment by Azurency** [comment]
You can post this directly in @astog repo I think https://github.com/astog/MoreLenses/issues

**Comment by datbunneh** [comment]
Done.

**Comment by datbunneh** [comment]
@Azurency That repository seems to be completely dead now so I'll reopen this one here.

**Comment by datbunneh** [comment]
@Azurency It seems @astog is back and he has already done it.
