### ISSUE TITLE
can't select or dismiss a city to change anything

### ISSUE THREAD

**Issue by trismyth** [Azurency/CQUI_Community-Edition#224]
great idea, however i am unable to close the production queue side bar using the 'x', instead i have to click a unit to take me away from the city. and i am unable, from the first turn onward select a city to either manage citizen focus/change production/buy land tiles etc.
i have removed the other production queue mod...
any known conflicting mods?

**Comment by oerms** [comment]
Please try disabling all other mods and create the same behaviour.
Then enable other mods one by one to determine which is causing the problem. 
After that please report with providing a safegame and detailed information of mods used. Thanks!
