### ISSUE TITLE
"Please Wait" status when moving to next turn remains despite next turn starting.

### ISSUE THREAD

**Issue by joeross-12** [Azurency/CQUI_Community-Edition#227]
No other mods active, bug started with most recent Fall patch from Firaxis. 

Immediately when starting a new game, can click on "Next Turn" and game will process other players turns. When player starts turn 2, the bottom right icon remains as "please wait" and will not display any notifications or prompts for production/science/etc. 

Running game on OS X High Sierra

**Comment by volosator** [comment]
Same here. Problem started with the fall 2017 patch. OSX El Capitan.

Unable to perform any other action except move the unit. Please wait and no menu available.

Save game menu also seems to be broken, see the screen shot. 

No other mods are active.

<img width="1680" alt="screen shot 2017-11-19 at 14 49 19" src="https://user-images.githubusercontent.com/6540726/32994723-3a8ab6c6-cd39-11e7-81e7-c94902eeeb40.png">
<img width="1680" alt="screen shot 2017-11-19 at 14 49 45" src="https://user-images.githubusercontent.com/6540726/32994728-4bf26012-cd39-11e7-9b1b-78d2ea4aee3a.png">
<img width="1680" alt="screen shot 2017-11-19 at 14 49 50" src="https://user-images.githubusercontent.com/6540726/32994732-5a62dabe-cd39-11e7-8ee9-fc75d736bc5b.png">

**Comment by Brentj0hns0n** [comment]
I am experiencing this "Please Wait" status error at the beginning of games as well.

Running on steam on Linux (Ubuntu) with no other mods.

**Comment by nielsjansendk** [comment]
Same problem, I am on a Mac with OSX "High Sierra".

**Comment by irishbs** [comment]
Also ran into this problem on my Mac OSX Sierra 10.12.5,  volosator's 1st image is on point.

**Comment by Azurency** [comment]
Will test and fix this on my Mac soon. I think I'll make a specific branch for macOS like before.

**Comment by charlesfollett** [comment]
Same issue present on linux

**Comment by Theaitetos** [comment]
The bug appeared before the Fall patch and was fixed; seemed to be a case sensitivity issue on Linux/Mac: [github.com/CQUI-Org/cqui/issues/575](https://github.com/CQUI-Org/cqui/issues/575).

**Comment by volosator** [comment]
Is there anything I can help with? I can collect debug if you point me to an article on how to do it.

**Comment by rodfrod** [comment]
Any news? I'm getting same problem. Mac High Sierra.

**Comment by Azurency** [comment]
I'm confused, someone said "with the fall 2017 patch" but the patch is not here yet for Mac/linux, are you all using the latest compatible version for the summer patch here https://github.com/Azurency/CQUI_Community-Edition/releases/tag/summer-version ? It's working fine for me.

**Comment by nielsjansendk** [comment]
I tried removing my subscription from Steam workshop, deleted all mods, plus the Mods.sqlite database, installed the summer patch version as @Azurency suggested, and I actually got it to work. I think the key was removing the sqlite database, although YMMV.

**Comment by rodfrod** [comment]
Thanks!!! It worked for me too, on Mac High Sierra https://github.com/Azurency/CQUI_Community-Edition/releases/tag/summer-version

**Comment by Brentj0hns0n** [comment]
Thanks!  
I was able to get it to work in Linux by manually installing the files from the "summer-version" stream.

Just find the mod files on your system and replace them with the linked version;  leave the mod enabled.
At least that is what worked for me!
