### ISSUE TITLE
Production queue after buying a building by faith

### ISSUE THREAD

**Issue by MauiSven** [Azurency/CQUI_Community-Edition#229]
If you buy a building with faith, the current construction order is deleted from the production queue. If there are more orders in the queue, they will moved up.
**UPDATE**: That seems to fall apparently only repair orders. 

See following figures:

Before:
![queue before](https://user-images.githubusercontent.com/31672167/32991772-485937d8-cd42-11e7-8cb8-4ecace92089c.JPG)

After:
![queue after](https://user-images.githubusercontent.com/31672167/32991777-4e6fd578-cd42-11e7-8ecf-2e088de3ad53.JPG)

Following DLC and Mods are used:
![image](https://user-images.githubusercontent.com/31672167/32991832-12b284c6-cd43-11e7-9339-f1666392f19a.png)

**Comment by Azurency** [comment]
Related to #112
