### ISSUE TITLE
Espionage screens list non-available targets

### ISSUE THREAD

**Issue by ricanuck** [Azurency/CQUI_Community-Edition#234]
Both the espionage overview and the target selector screens list cities, and display district icons even for cities/districts where the target has been disabled. Example: you are looking for Space ports to disrupt with your spy. Your enemy civ has built the Space port in three of his cities, and two of them are already disabled; both the overview and the selector will list ALL three cities and show the Space port icon as if they were available targets. The user has to go to each city and visually confirm on the map that the target is disabled or if it is a valid, enabled target.

**Comment by ricanuck** [comment]
See? I told you. I am enjoying this little change for more than 10 days now, and the huge CQUI community cannot because you think it is better to pass through each original mod creator... the original CQUI did its own customizations, based on the clear fact that once the permission to integrate was given, we could do whatever we wanted with the now CQUI-custom version of mod X. It worked perfectly, and produced, in example, custom versions of IDS and URS that are far richer and better than the original mods.

I will continue to post my modifications under that assumption. If you still feel that we have to go to the original modders for everything we do, you are basically disallowing the CQUI users of great additions, as this little case proves.

I encourage you to reconsider, and go back to the successful original CQUI spirit, or in any case, consider what I already asked you: open up the merging into this repository to more people, so that we don't have this situations anymore.

**Comment by Azurency** [comment]
Well, you're right on the fact that I think we've waited long enough 👍. 
I'll merge your changes directly here and leave a comment on the pull request on @astog repo. 
Still I think it's the right to do to go first to the orignal creators of the mod if it's still maintained (which is not the case for the example you're using : IDS, URS, ...).
