### ISSUE TITLE
cannot access the build menu 

### ISSUE THREAD

**Issue by FrankLavoie** [Azurency/CQUI_Community-Edition#237]
If you build a wonder whether in queue or actual and another player/AI finishes it before you ...  the build menu (right side city menu) in that city is inaccessible.

![civ6screen0000](https://user-images.githubusercontent.com/34221818/33531524-35471938-d85c-11e7-94f3-b8e2494a7364.jpg)

**Comment by vunhan** [comment]
Same here. :(

**Comment by hangman04** [comment]
same as @CzarnyDar

**Comment by thomco** [comment]
Same.   Playing Persia.  Pick Stonehedge, and the build menu never comes back

**Comment by thomco** [comment]
It seems to have been introduced with commit e7255890d50855157745db8cd792c3a6183d601b to fix #220 

If I revert the changes from that commit, the production panel reappears
Also, I think this may only repro when building a wonder in a city that does not yet have any Disticts

**Comment by JustNilt** [comment]
I got it just now in a city with districts.  The odd thing is I'm playing with most of my mods disabled for the first time today in order to test some things and it only just started happening.  I'll have to play around with re-enabling those one at a time.  Maybe one of them fixes it inadvertently.

**Comment by Azurency** [comment]
Should be fixed now

**Comment by FrankLavoie** [comment]
Thanks will re-enable the mod and run some tests.  Have a Great day!

**Comment by FrankLavoie** [comment]
managed to repeat  the process and all is good.   Well done m8!  Hope to get some awesome games under my belt now ... play on and Stand the Test of Time!
