### ISSUE TITLE
Better automatic unit cycling

### ISSUE THREAD

**Issue by the-sn-man** [Azurency/CQUI_Community-Edition#239]
When Unit A finishes it's moves and automatic unit cycling is on, the game will sometimes momentarily shift to Unit B for a split second before switching to Unit C and allowing you to perform Unit C's moves. This sometimes causes problems where the user will mis-input a command intended for Unit B instead to Unit C. It often does this repeatedly, and between after every unit's moves, it will switch to Unit B before switching again to Unit D, E, F, etc.

**Comment by oerms** [comment]
I second this. This behaviour is highly annoying! If this could be fixed, that would be wonderful!

**Comment by Azurency** [comment]
Yes, this is annoying, can you try the fix I pushed in #244. It should be better now, but we have to test it.

**Comment by oerms** [comment]
This seems to be working very well. I am not noticing the same annoying behaviour as before. Great work!
