### ISSUE TITLE
Can't make peace deal [bug]

### ISSUE THREAD

**Issue by jebwatson** [Azurency/CQUI_Community-Edition#246]
Having issues with the trade screen while attempting a peace deal. This was working earlier in the same game so I think it must be an issue triggered by dismissing the trade screen after the AI opens the trade screen automatically. Closing the menu before it loads? Closing it with ESC? Hard to pin this one down, but it only affects this particular trade screen (victoria who I am at war with). I have disabled the mod and that solves the issue so it's definitely a mod issue. I've attached screenshots and the save.
[Issues.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1557642/Issues.zip)

**Comment by ricanuck** [comment]
If you know how to manually install the mod, download the latest master zip and install into your mod folder. This bug has been potentially fixed a week ago or so.

**Comment by Azurency** [comment]
Sparrow also updated the steam version so it should be fixed on steam too now.
