### ISSUE TITLE
City Details Screen

### ISSUE THREAD

**Issue by CheTranqui** [Azurency/CQUI_Community-Edition#248]
Initially the City Details panel didn't show up when I clicked on a city.

After a full restart, the panel shows up, but declares that all cities are starving, and it doesn't show any actual numbers.  Housing, for instance, is stated as " - Housing for -- ".  Basically, although the skeletal structure of a City Details panel is present, none of the information is actually filled in.

![city details error](https://user-images.githubusercontent.com/26752931/34082767-726b3b10-e332-11e7-930d-b3bae1b9399d.jpg)

**Comment by CheTranqui** [comment]
On my next turn, the City Details panel broke again - it no longer appears when I click on a city... same issue that I had initially:  it just doesn't show up.

... I also cannot see my citizens and thus reassign them manually.

**Comment by ccjmne** [comment]
Yup, this is also happening to me.

**Comment by ccjmne** [comment]
@CheTranqui would you happen to be using "Original Owner At A Glance" alongside CQUI?
Enablind OAAG when using CQUI has had with me the same effects you're describing.

**Comment by CheTranqui** [comment]
Ya know, I just tried out that mod recently...  ...and just upgraded to the most recent CQUI...  You are wise.  I'll drop the other addon - excellent observation - I was wondering why a streamer of mine wasn't having the same issue I was.  Seems odd that OOAAG would interfere with THAT screen!
