### ISSUE TITLE
Government Sprite Duplication in Civics Tree

### ISSUE THREAD

**Issue by aislingdailey** [Azurency/CQUI_Community-Edition#253]
When completing a civic, the civic tree becomes populated with government types which extend horizontal for the length of the civic item and infinitely downwards starting from the vertical position of the object. This can be resolved by exiting to the main menu and reloading the save but returns when the next civic is completed.

[Here's an example of what I'm talking about](https://puu.sh/yPCrd/ed56bb7c38.jpg).

* Windows 10 Home (64-bit) 
* Civilization VI v1.0.0.194 (Build 313929)
* Additional mods: [Hidden Agendas Expansion](https://steamcommunity.com/sharedfiles/filedetails/?id=931656288&searchtext=hidden+agendas)

Additionally, I should note this occurred in a hotseat game. I have not tested it in other modes. You can view my zipped configuration here: https://transfer.sh/U262M/options.zip

EDIT(2017-12-28): Fixed broken example link.

**Comment by Azurency** [comment]
I'm sorry I'm replying a little late, do you still have this issue ? Does it happen when you only have CQUI enabled and no other mod ?

**Comment by aislingdailey** [comment]
Correct - I've tried isolating CQUI with no success.

**Comment by Azurency** [comment]
Is it still happening with the latest versions ?
