### ISSUE TITLE
Production Queue: Enemy on District

### ISSUE THREAD

**Issue by longironcondor** [Azurency/CQUI_Community-Edition#269]
I noticed the city production queue becomes glitched when attempting to queue a building on a district that has an enemy on it. The base game doesn't let you build on a district with an enemy, but here it is still possible to add such buildings to the queue.

Attached save game with enemy on Campus district of Osaka. Production of last item completes, and then please attempt to queue to build a library.

[AutoSave_0102.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1633624/AutoSave_0102.zip)

**Comment by Azurency** [comment]
Should be fixed on the latest version here on GitHub
