### ISSUE TITLE
Cannot place districts after Fall Update on Mac

### ISSUE THREAD

**Issue by spb35** [Azurency/CQUI_Community-Edition#270]
the fall 2017 update recently went live for Mac and with the cqui mod enabled i am unable to produce districts or wonders or anything outside of my city center. ive narrowed it down to this mod. any help would be massively appreciated as i LOVE this mod. thanks

**Comment by Azurency** [comment]
Are you using the latest version of the mod ? Not the summer version that was working with the previous update.
I just tested and the latest version seemed to be working on my Mac.

**Comment by spb35** [comment]
how can I tell if I'm using the latest version? 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Antoine Lassier <notifications@github.com> Date: 1/16/18  16:00  (GMT-05:00) To: Azurency/CQUI_Community-Edition <CQUI_Community-Edition@noreply.github.com> Cc: spb35 <seanbuehler4@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Azurency/CQUI_Community-Edition] Cannot place districts after Fall Update on Mac (#270) 
Are you using the latest version of the mod ? Not the summer version that was working with the previous update.

I just tested and the latest version seemed to be working on my Mac.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Azurency/CQUI_Community-Edition","title":"Azurency/CQUI_Community-Edition","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Azurency/CQUI_Community-Edition"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Azurency in #270: Are you using the latest version of the mod ? Not the summer version that was working with the previous update.\r\nI just tested and the latest version seemed to be working on my Mac."}],"action":{"name":"View Issue","url":"https://github.com/Azurency/CQUI_Community-Edition/issues/270#issuecomment-358103856"}}}

**Comment by gherald** [comment]
Delete the current version in your mods folder, and then (only AFTER you have deleted it) subscribe too this mod in Steam or follow the manual installation instructions

**Comment by Azurency** [comment]
This should be fixed by installing the last version
