### ISSUE TITLE
Rise and Fall support question

### ISSUE THREAD

**Issue by wayneb64** [Azurency/CQUI_Community-Edition#273]
The first issue is there is no thread in Civ6 - Released Mods to discuss this mod hence this issue.

Once Rise and Fall drops in a couple weeks, will there be two flavors of this Mod? 
If not who wins/loses? 

I don't even want to buy/install the new enhancement until CQUI is ready to support it.

I also don't want to lose support for the base game during the time in between release and support.

Have their been any discussions on this I may have missed?

**Comment by ProustIdee** [comment]
It will probably come with a big patch, so it's likely CQUI won't work with the base or the expansion.

After that, no idea. Maybe a stable version for the base game (no new features) and a WIP version for the DLC?

**Comment by wayneb64** [comment]
I would just like to know the path of least resistance which will keep me playing some version of Civ VI with a working CQUI.

**Comment by ricanuck** [comment]
@wayneb64 : just before RaF release, grab a copy of the master .zip file from here, and that shall be your CQUI copy for the base game until something new happens. Make yourself comfortable installing the mod manually; it's better to do it that way anyways, because you don't need to wait for Steam workshop updates.

**Comment by wayneb64** [comment]
I grabbed a copy now to be sure I have one, but if the release drops a patch to Vanilla that breaks this version I am hosed either way right? This zip is only in case a new CQUI is dropped for the RaF version and breaks my game if I don't get the release? In that case I will just upgrade my game.

**Comment by sparrow8332** [comment]
Im waiting on 2K Games to give me a beta code so we can at least see where we stand with the expansion.

**Comment by oerms** [comment]
I suggest turning off automatic updates to the game and wait for a confirmation that CQUI works with both the new expansion and the possibly updated base game.

**Comment by wayneb64** [comment]
I don't see an option to disable updates for this game in Steam, just three flavors of when to update it.

**Comment by oerms** [comment]
I must have missed this. Sorry to lead you on a wrong path. :/

**Comment by wayneb64** [comment]
No problem, just trying to prevent being burned again by Firaxis, every time the 'fix' the game they end up breaking it. Playing without CQUI is really annoying to me.

**Comment by ricanuck** [comment]
@wayneb64 : we WILL be burned once again by Firaxis, that is a given. To make things worse, I am withholding my decision to buy this time due to their horrible performance so far with regards to bugs and fixes, and towards the modding community. So, I would not be able to contribute anything until that decision changes, and if someone else in the team is thinking the same way, who knows... we shall see what happens.

**Comment by ricanuck** [comment]
@sparrow8332 : you are waiting for Firaxis to give you access to the beta? I hope you are sitting while you wait...
They will NEVER give us access to a beta... I don't think they like modders that show how much better their product can be and how it should be coded... the same happened to Gazebo and his Vox Populi team, even after they clearly took many ideas for civ 6 from their mod...
SO, please sit while you wait... Arthritis is a painful illness.

**Comment by sparrow8332** [comment]
@ricanuck i fell asleep waiting lol looks like its going to be catch up game like always but i do hope this time they get things right and not break more than they fix but im not getting my hopes up though

**Comment by ricanuck** [comment]
@sparrow8332 : wanna bet? I go 50$ that they will break much more than they fix, IF they fix anything...

**Comment by wayneb64** [comment]
The patch came out yesterday and I see a few bugs have been opened, have any modders had a chance to look at the changes to get a feel for the size/scope of the fixes needed for the base game?

Will the base game be repaired first or skipped in favor of supporting the expansion? Would there be a fork for the expansion in the first case?

**Comment by Azurency** [comment]
see #283
