### ISSUE TITLE
can't open city management

### ISSUE THREAD

**Issue by Haku-Shimapans** [Azurency/CQUI_Community-Edition#275]
Whenever I click on my city banner I can't open city management. I checked to see if it's conflicting mods but it isn't.

**Comment by joranamael** [comment]
Same problem, especially on scenarios

**Comment by Azurency** [comment]
It's happening only on scenarios ? Can you upload a save game so that we can test it ?

**Comment by Haku-Shimapans** [comment]
for me it's in every game not just scenarios. I don't know if that will show you or now.

**Comment by joranamael** [comment]
Yep, only on scenarios for me, here is the save, just rename it without the .jpg (GitHub restriction...)
![ghaznevides 12 904 ap j -c civ6save](https://user-images.githubusercontent.com/36113165/35774444-f5231e16-096f-11e8-97d8-0e60e310b2d5.jpg)
