### ISSUE TITLE
Unit movement not working with right clicks [Patch 1.0.0.216]

### ISSUE THREAD

**Issue by eporres** [Azurency/CQUI_Community-Edition#278]
With a unit selected, right clicking on a tile draws the path from the unit to that tile, but no longer causes the unit to move.

I apologize in advance if this this not the right way to go about this, but I figured having separate issues for each of the bugs introduced with the latest patch (1.0.0.216) would be the best way to track these items.

**Comment by gonzalezea** [comment]
Same problem here. Very weird even with mod disabled, had to move folder out of /Mods

**Comment by Azurency** [comment]
part of #283
