### ISSUE TITLE
Unable to open Civics Tree [Patch 1.0.0.216]

### ISSUE THREAD

**Issue by eporres** [Azurency/CQUI_Community-Edition#279]
Clicking on the the current civic being researched and/or the dedicated button on the top left both fail to open up the Civics Tree.

I apologize in advance if this this not the right way to go about this, but I figured having separate issues for each of the bugs introduced with the latest patch (1.0.0.216) would be the best way to track these items.

**Comment by Azurency** [comment]
part of #283
