### ISSUE TITLE
Unable to add pin to the map [Patch 1.0.0.216]

### ISSUE THREAD

**Issue by eporres** [Azurency/CQUI_Community-Edition#280]
Clicking on the 'Add Pin' button toggles its state to 'PLACING' but does not bring up the map pin popup once a tile is clicked. The button then returns to its 'Add Pin' state without having any effects.

I apologize in advance if this this not the right way to go about this, but I figured having separate issues for each of the bugs introduced with the latest patch (1.0.0.216) would be the best way to track these items.

**Comment by Azurency** [comment]
part of #283
