### ISSUE TITLE
World Tracker shows Blank and Unable to assign Envoys after Patch 1.0.0.216 fixes

### ISSUE THREAD

**Issue by FupaConQueso** [Azurency/CQUI_Community-Edition#282]
The world Tracker shows but it is empty for culture and science. I can click on them and they open up. Also when i get an envoy, it does not allow me to assign them to a city state. Last night i had 8 of them and the only envoys assigned were the ones i completed a city quest for. This was a rise and fall expansion game I was playing.

**Comment by Azurency** [comment]
part of #283
