### ISSUE TITLE
Unsubbed/Unfavorited On Workshop Page Mod Still In Game

### ISSUE THREAD

**Issue by WhiteSammy** [Azurency/CQUI_Community-Edition#291]
I can't figure out where I need to go to delete the mod. All the help I find online is not helpful for this. Everyone says to go to Steam/Steamapps/Workshop/Content or something similar and there is nothing. I search for civ6 mods or a workshop folder on my entire computer and can't find it anywhere.

CQUI shows up installed in game but not subscribed to. I've verified game files and reinstalled twice and it still shows up.

I have reached a breaking point, please help...

**Comment by oerms** [comment]
The two paths that come to my mind are:
...\steam\steamapps\common\Sid Meier's Civilization VI
and
<user>\Documents\My Games\Sid Meier's Civilization VI

**Comment by JCron245** [comment]
Have you tried disabling simply disabling it from the list of mods in the additional content menu in game?

[Example image of additional content menu](https://pbs.twimg.com/media/DRlqQcoX0AAG235.jpg:large)

**Comment by JCron245** [comment]
If you are trying to continue a save game that you had previously started with that mod I **_THINK_** that mod code is actually bundled up with the save. I can't verify that but I have had problems in the past that appeared to be the mod being a part of a save game I was continuing even though it had been deleted. Maybe someone else can confirm this...

**Comment by WhiteSammy** [comment]
No, it was not a saved game.

The game still has fps issues if i disable CQUI, I have to fully unsub and restart the game in order for it to go away the first time. 

I checked every path for steam and civ6 and none of them have files in any folders named content or mods.

**Comment by WhiteSammy** [comment]
I'm retarded. Forgot I moved my steam folder to my game SSD from my HDD.

Was looking in the wrong directory.
