### ISSUE TITLE
Every Bug I'm Experiencing With New Update

### ISSUE THREAD

**Issue by Kree6427** [Azurency/CQUI_Community-Edition#294]
-As soon as I start the game, a massive frame drop takes place.
-When I settle a city, the city doesn't display a name, population number, etc over the settlement.
-I cannot open production at all and there is no way to open it, so I can't go beyond the first turn.
-When I want to move my only warrior unit, I can't move it at all. The route is stuck to some space off the screen and I can't move it.
-When I disable the mod it seems to infect my game files and causes me to have low framerate, an unusable production button, and the disability to not be able to move my units or advance the turn.
-The only solution I found was to verify the game cache via steam.
-BTW I only run the DirectX12 version of the game.
-Overall, I can't use this mod and I will keep it away from my mod list until a fix is made.

**Comment by gipfeli** [comment]
#283
