### ISSUE TITLE
Hangs when creating a religion

### ISSUE THREAD

**Issue by trafenrest** [Azurency/CQUI_Community-Edition#295]
Load the saved game and activate the prophet to found a religion. This also finishes Theologiy.
With CQUI disabled, the pop-up messages for founding the religion an theology appear one after the other and you can continue to play.
With CQUI enabled, there are no popup messages and both infos are spoke at the same time over and over. Pretty nice sound effect, but you have to kill the CIV 6 process
[HOJO TOKIMUNE 104 300 v. Chr.CRASH.Civ6Save.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1749537/HOJO.TOKIMUNE.104.300.v.Chr.CRASH.Civ6Save.zip)

**Comment by JCron245** [comment]
If you have the latest update to the game and/or the Rise and Fall expansion the team is still working to make the mod compatible with the new changes. They have an open issue you should post your problem in if that is the case https://github.com/Azurency/CQUI_Community-Edition/issues/283

**Comment by trafenrest** [comment]
Not Rise and Fall but the latest patch of the game.
The reported problem is in CQUI_Community-Edition-Patch-1.0.0.216

**Comment by trafenrest** [comment]
Did you fix it or couldn't you reproduce it?

Because I can reproduce it without the steam version [https://github.com/Azurency/CQUI_Community-Edition/issues/283#issuecomment-369338744](url)

**Comment by Azurency** [comment]
Have you tried the latest version, it's fixed

**Comment by trafenrest** [comment]
Yes, it's fixed.
Thank you!
