### ISSUE TITLE
City State List and World Tracker

### ISSUE THREAD

**Issue by HalitUzuner** [Azurency/CQUI_Community-Edition#303]
Hi, 
City state list shows only first state you encountered and don't let you give any envy. And World tracker at the left top off the screen doesn't show any tech or civics progress.

**Comment by Azurency** [comment]
Are you on Rise and Fall ? Or playing on the base game (without Rise and Fall)

**Comment by HalitUzuner** [comment]
I'm playing with rise and fall ruleset

**Comment by HalitUzuner** [comment]
Used a "reveal all" command after few turns and as you can see at the picture, tech and civics processes aren't shown and city state list doesn't show all the states.
 
![2018-03-05_07-30-34](https://user-images.githubusercontent.com/20402974/36957737-975d247c-2047-11e8-933b-3b9ab2405064.png)

**Comment by Azurency** [comment]
CQUI is not compatible with Rise and Fall yet, see #283
