### ISSUE TITLE
Unprocessed links in the city-state report

### ISSUE THREAD

**Issue by slathos** [Azurency/CQUI_Community-Edition#307]
After meeting the first city state, its report screen shows unprocessed $$ links. Details in image attached.

To reproduce: try playing as German Empire and discover city-state first.
![image](https://user-images.githubusercontent.com/25015531/37169973-d95c342a-2309-11e8-9652-08e47a475dc6.png)

**Comment by ihendriks** [comment]
The mod is not compatible with Rise and Fall yet.

**Comment by Dragget** [comment]
I'm seeing this same issue with the base game.

**Comment by Azurency** [comment]
See #283 should be fixed with the latest version.

**Comment by Dragget** [comment]
Looks like a new version was just uploaded... That fixed it. Thanks for the heads up.
