### ISSUE TITLE
Problems with new update

### ISSUE THREAD

**Issue by thyeestes** [Azurency/CQUI_Community-Edition#308]
Today I received an new update .229 which makes a mess of things again. Units not don't show their health on the map, unable to open city screen and then I stopped playing.

**Comment by wayneb64** [comment]
Was that an R&F patch or a Vanilla patch or both?

**Comment by thyeestes** [comment]
In Vanilla. I don't have R&F

**Comment by Azurency** [comment]
See #283 for the update.
