### ISSUE TITLE
City States Panel not showing properly

### ISSUE THREAD

**Issue by MeeraXI** [Azurency/CQUI_Community-Edition#309]
All of a sudden my city states panel is not functioning. 
I removed the mod and it was fixed. I added only this mod again and I have the same problem.
I couldn't find an option that could change settings in city states. Maybe I missed something.
Before this issue the mod worked perfectly for me. 
Now I can't play with the mod anymore, because I can't access any of the city states and send envoys. The back button at the top right corner doesn't work.

![screen shot 2018-03-09 at 15 40 15](https://user-images.githubusercontent.com/37216076/37210192-7ef31a6a-23b0-11e8-8dc3-31cb2473d879.png)

**Comment by Azurency** [comment]
Fixed on GitHub, see #283 an update will soon be made on Steam by Sparrow.
