### ISSUE TITLE
City states screen does not list all city states and can't assign envoys

### ISSUE THREAD

**Issue by Nijin22** [Azurency/CQUI_Community-Edition#321]
Two (possibly related) issues:
The city state screen does not list all city states:

![image](https://user-images.githubusercontent.com/6653765/38782586-1d00c844-40f6-11e8-833f-e252950646d5.png)

I'm not able to assign envoys (clicking the arrow does not do anything):
https://gfycat.com/CalmKeenChickadee

Mod version is: 3df8664bbafaca065257e972d93335101cad6025
I don't have other UI mods
Game version is 1.0.0.229 with Rise & Fall DLC

Thanks for your work on the mod!

**Comment by rasputinoz** [comment]
this seems to have become active since the latest Patch. Wasn't an issue until playing today.

**Comment by ihendriks** [comment]
The R&F version of the mod hasn't been updated for the Spring patch yet, so you'll have to wait until that's taken care of.

**Comment by mithlug** [comment]
This still seems to be a problem, downloaded CQUI from steam recently and I have this problem too.

**Comment by mithlug** [comment]
Fixed this by making both files in 289070\1125169247\Assets\UI\PartialScreens gibberish filenames. So the game doesn't read those files and now envoying works as normal. Temporary workaround.

**Comment by Azurency** [comment]
see #283

**Comment by dan-boehm** [comment]
This is still occuring for me using the latest version on steam.

**Comment by ihendriks** [comment]
@Boehemyth Could you upload a savegame and your logs from `..\Documents\My Games\Sid Meier's Civilization VI\` for us? We'll take a look at those to see what the issue is.

**Comment by chadsten** [comment]
I'm having the same issue. Just installed R&F, enabled this mod for the first time and I'm experiencing the same bug. 

https://www.dropbox.com/sh/6ag363gywbjxep1/AABjhCNPXN9zvjJMLF5fUgxLa?dl=0

Game save and log there. Just let me know if you need any other info.

Edit: I can confirm the solution of renaming the contents of UI\PartialScreens solves the problem.

**Comment by ihendriks** [comment]
>@chadsten wrote: 
> I'm having the same issue. Just installed R&F, enabled this mod for the first time and I'm experiencing the same bug.
> 
> [dropbox.com/sh/6ag363gywbjxep1/AABjhCNPXN9zvjJMLF5fUgxLa?dl=0](https://www.dropbox.com/sh/6ag363gywbjxep1/AABjhCNPXN9zvjJMLF5fUgxLa?dl=0)
> 
> Game save and log there. Just let me know if you need any other info.
> 
> Edit: I can confirm the solution of renaming the contents of UI\PartialScreens solves the problem.

You can get around the issue by either disabling YNAMP, or enabling the official DLC (I don't know which one, haven't been able to test it). I can't narrow it down any further for now, sorry.
