### ISSUE TITLE
'City Status' not displaying correctly bug?

### ISSUE THREAD

**Issue by jonpfl** [Azurency/CQUI_Community-Edition#323]
All,

The 'City Status' is only displaying ONE city and it has labels in the cells instead of data (ie '$Housing$', '$Amenities$', etc).

![image](https://user-images.githubusercontent.com/30752966/39086151-82464120-455b-11e8-82cb-9569e46a8230.png)

Thx
jonpfl

**Comment by Azurency** [comment]
see #283
