### ISSUE TITLE
Science and civic won't show on the screen

### ISSUE THREAD

**Issue by Asyzgany** [Azurency/CQUI_Community-Edition#326]
![desktop screenshot 2018 04 28 - 18 52 34 81](https://user-images.githubusercontent.com/38674031/39401856-880d2a64-4b15-11e8-8fc4-4d7048bd8d65.png)
![desktop screenshot 2018 04 28 - 18 52 39 13](https://user-images.githubusercontent.com/38674031/39401857-8818d81e-4b15-11e8-8695-3e63f2ebca9c.png)
This is without any mods enabled other than CQUI, so I know that it is not another mod messing up... the Tech and civics will still progress, but you cannot see them unless you click on the banner for it. It's just an annoyance, so I would say this is low on the urgency list

**Comment by Asyzgany** [comment]
yeah, redownloaded mod, and now it works fine.

**Comment by KotoTheMage** [comment]
I have a freshly installed Civ6 + Rise and Fall. I'm not subscribed for any 3d party dlcs/mods in steam. The mods folder ("Documents/.../My games/Sid Meier's Civilization VI/Mods") is empty when I copy the lastest CQUI mod.
Still the issue persist as another person described above. No research window and can't send envoys.
I'm playing English version of the game on Russian OS (Windows 10). Maybe it has something to do with the issue?

**Comment by ihendriks** [comment]
@KotoTheMage Can you check in the steam workshop folder to see if it's there? You can find the steam workshop folder of Civ 6 in `..\steam\steamapps\workshop\content\289070\`, and the mod itself has number `1125169247`.

If that folder exists, delete it and see if that sorts out the issue. If it doesn't than let us know.

**Comment by KotoTheMage** [comment]
@ihendriks C:\Program Files (x86)\Steam\steamapps\workshop\content\289070 is empty for me.

**Comment by ihendriks** [comment]
@KotoTheMage Can you post your logs and savegame here? You can find them in `..\documents\my games\sid meier's civilization vi\`. I'll take a look at them and see if I can figure this one out.

**Comment by KotoTheMage** [comment]
@ihendriks Thank you for taking your time to figure this out, much appreciated. Here's the files you asked.
[ArtDef.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990121/ArtDef.log)
[AStar_APP.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990122/AStar_APP.log)
[AStar_GC.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990123/AStar_GC.log)
[BlockerLog.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990124/BlockerLog.log)
[CultureBordersLog.txt](https://github.com/Azurency/CQUI_Community-Edition/files/1990125/CultureBordersLog.txt)
[Database.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990126/Database.log)
[DynGeoLog.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990127/DynGeoLog.log)
[Engine.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990128/Engine.log)
[FiraxisLive.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990129/FiraxisLive.log)
[GameCore.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990130/GameCore.log)
[GameCoreAppConfig.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990131/GameCoreAppConfig.log)
[LoadGameViewState.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990132/LoadGameViewState.log)
[Localization.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990133/Localization.log)
[Lua.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990134/Lua.log)
[Modding.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990135/Modding.log)
[net_connection_debug.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990136/net_connection_debug.log)
[net_message_debug.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990137/net_message_debug.log)
[Renderer.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990138/Renderer.log)
[Startup.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990139/Startup.log)
[SynthesisLog.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990140/SynthesisLog.log)
[UnitOperations.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990141/UnitOperations.log)
[UserInterface.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990142/UserInterface.log)
[VisManagerErrors.log](https://github.com/Azurency/CQUI_Community-Edition/files/1990143/VisManagerErrors.log)

[CQUI_PETER.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1990144/CQUI_PETER.zip)

**Comment by moepmoep12** [comment]
I'm having the same issue and additionally I can't send envoys and pressing "Escape" doesn't bring up the main menu.

**Comment by ihendriks** [comment]
@KotoTheMage You are loading the wrong version of the mod. You need to select the Expansion1 branch when you download it on github. You can find the correct version here: [CQUI/Expansion1](https://github.com/Azurency/CQUI_Community-Edition/archive/expansion1.zip)

**Comment by ihendriks** [comment]
@moepmoep12 Can you follow the steps I provided throughout this comment chain and let me know how that goes?

**Comment by KotoTheMage** [comment]
@ihendriks oh, snap. thanks a lot!

**Comment by moepmoep12** [comment]
oh dear, of course!
