### ISSUE TITLE
CQUI Expansion 1, Can't Expand and Open Tech Tree

### ISSUE THREAD

**Issue by therealcrow999** [Azurency/CQUI_Community-Edition#329]
With today's (5/10/18), new update. The Tech Tree can't be open to be expanded. For example if a Tech I researched is done and I click to see Recommended and then I click up top to expand and see the whole Tech Tree, it won't open. The Civic Tree seems to be working fine. 

Thanks.

**Comment by wayneb64** [comment]
Back to offline mode I guess, I managed to interrupt the update and it says "Update paused". Anyone know if my game is hosed now or does it download first and then modify later?

Does this break Vanilla or R&F or both?

**Comment by whitenoise500** [comment]
It seems both as I'm having the same issue with vanilla...

**Comment by rasputinoz** [comment]
Yes same problem. Cant open Tech Tree.

**Comment by MarkusKV** [comment]
Ditto.  Using the spring drop and the tech panel does not open.  Civics panel opens fine.

**Comment by pspjuth** [comment]
[techtree.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1994275/techtree.zip)
Attached is a fixed techtree.lua that works for me. For some reason I cannot push a pull request right now.

**Comment by trafenrest** [comment]
Works for me too, after I copied it to `...SteamLibrary\steamapps\workshop\content\289070\1125169247\Assets\UI\Screens`

**Comment by therealcrow999** [comment]
@pspjuth Thanks for the fix! I put it in my CQUI_Community-Edition-expansion1 folder and it works fine.

**Comment by wayneb64** [comment]
Will that fix work for the Vanilla version of CQUI in the main branch or is a different fix needed?

**Comment by whitenoise500** [comment]
This fix works for vanilla.  Just tried it.

**Comment by pspjuth** [comment]
I merged the game file changes into the master branch version of that file.
I don't have R&F yet, but I haven't noticed any obvious problems in the base game,
except for the one fixed here.

**Comment by rasputinoz** [comment]
sadly doesn't work in RF .  will have t o wait

**Comment by rasputinoz** [comment]
Seems to be working with RF now. gotta hate computers sometimes.

**Comment by totteluva** [comment]
Even after installing the techtree zipfile it does not work for me, I have a Mac though. What can I do to fix it? :)

**Comment by rasputinoz** [comment]
Buy a windows machine lol.  Sorry just kidding

Sent from my iPhone

On 7 Jun 2018, at 7:21 pm, totteluva <notifications@github.com<mailto:notifications@github.com>> wrote:


Even after installing the techtree zipfile it does not work for me, I have a Mac though. What can I do to fix it? :)

**Comment by evandy0** [comment]
another mac user for whom the updated techtree.lua did not fix the issue.

Also have the World Tracker display issue noted above.   It's a shame, as I really like the CQUI much better than what comes with 6...

**Comment by flavius** [comment]
I confirm, the fix does not work on all platforms.

**Comment by scorpnet** [comment]
Mac user here, Ive tried the Mac update, the tech tree Lua, and offline mode. Still not working as of today. help!

**Comment by dcrabill** [comment]
Installed CQUI_Community-Edition-expansion1 mod and techtree.zip on Windows10 machine. Can see Civics Tree, but cannot see Tech Tree.

**Comment by AlvinFark** [comment]
I made the fix for anyone who hasn't found any.
Copy this into your mod file, it will reset your tech tree and world overview to default UI
[panel.zip](https://github.com/Azurency/CQUI_Community-Edition/files/2173231/panel.zip)

**Comment by JouresKoh** [comment]
OS: Windows 10
DLC: Vanilla and R&F
Game Version: 1.0.0.257(349140), Traditional Chinese Version
Mod: CQUI Beta with or without any other mod

I still can't access full Tech Tree panel, even with or without the techtree.lua patch. I can select the tech from the left quick tech selection panel, but I can't expand the full tech tree.

![tech tree](https://user-images.githubusercontent.com/29336184/42418335-555a61fc-82d0-11e8-8219-229a9c707e76.jpg)

**Comment by AlvinFark** [comment]
@JouresKoh is it possible that it has something to do with the language you're using?

Anyway try copy the techtree lua and xml from your base game directory into the respective folder in the mod, that will reset the tech tree into your default UI. that's what I actually did

**Comment by ihendriks** [comment]
> @AlvinFark 
> Anyway try copy the techtree lua and xml from your base game directory into the respective folder in the mod, that will reset the tech tree into your default UI. that's what I actually did

You can just remove the files from the mod and it'll use the the base game versions.

> @JouresKoh 
> OS: Windows 10
> DLC: Vanilla and R&F
> Game Version: 1.0.0.257(349140), Traditional Chinese Version
> Mod: CQUI Beta with or without any other mod
> 
> I still can't access full Tech Tree panel, even with or without the techtree.lua patch. I can select the tech from the left quick tech selection panel, but I can't expand the full tech tree.

If you are using the beta version on steam: it's not compatible with R&F. It should work with Vanilla though. If you are subbed to both the beta and normal CQUI versions on steam you might also run into conflicts, so you should try unsubbing from one or the other.

The CQUI Beta on steam is also not maintained by us (it's the same mod, but a different uploader, so it might not stay up to date if we start patching stuff).

**Comment by JouresKoh** [comment]
> @ihendriks
> If you are using the beta version on steam: it's not compatible with R&F. It should work with Vanilla though. If you are subbed to both the beta and normal CQUI versions on steam you might also run into conflicts, so you should try unsubbing from one or the other.

Wow, Big thanks to you~ it actually work after I have unsubscribe the normal CQUI mod. Thank you very much, you save my day.

> The CQUI Beta on steam is also not maintained by us (it's the same mod, but a different uploader, so it might not stay up to date if we start patching stuff).

Ya, I'm aware of that, I have been constantly following the latest news of CQUI, I understand that the creator is working alone without too much of help, I will wait patiently until the mod fully support for the whole game~

**Comment by Xerus2000** [comment]
I am here and since I actively play Civ with CQUI I don't plan on stopping to update CQUI Beta. However, I'd readily hand it over or take it down when the original is maintained properly.

**Comment by Azurency** [comment]
see #283
