### ISSUE TITLE
City Panels Not Showing - No Rise & Fall

### ISSUE THREAD

**Issue by Johnson84025** [Azurency/CQUI_Community-Edition#330]
For some reason, my city panels are not showing and I am 99.99% it is a user error. I could use some help with finding where I messed up though.

I do not believe that I have any conflicting mods and I attempted to use steam and manual install, I also followed install instructions.

Below are my mods and add-ons for the game as well as a screenshot of my city view:
- DLC: Australia Civilization Pack
- DLC: Aztec Civilization Pack
- DLC: Vikings Content
- AI+
- Caps Lock
- City Roads
- Community Quick User Interface [duh]
- Dynamic Diplomacy (Updated)
- Immersive Dialogue
- Moar Units
- Quik Start
- R.E.D. Modpack
![no city panels](https://user-images.githubusercontent.com/39174431/39898950-6e67c2f8-5476-11e8-8a93-af8bafe783d4.PNG)

**Comment by Johnson84025** [comment]
@Azurency can you assist me?

**Comment by ihendriks** [comment]
Choarace doesn't work on this project anymore.

The best thing you can do is try the game without any mod (except for CQUI), and see if the issue persists. If it does, please upload your savefile and logs here. You can find them in `..\documents\my games\sid meier's civilization vi\`. Let me know how that goes.

**Comment by JavaShipped** [comment]
I am also having this bug!

**Comment by ihendriks** [comment]
@JavaShipped Can you do as I asked above?

**Comment by Azurency** [comment]
see #283
