### ISSUE TITLE
Scout Lens not working for Non standard scouts  - Possibly fixed 

### ISSUE THREAD

**Issue by rasputinoz** [Azurency/CQUI_Community-Edition#338]
Scout Lens not working for Non standard scouts eg. Scythian Empire

This is Vanilla issue not running RF for this game and no lens becomes activated when scout is active.

**Comment by BlackSmokeDMax** [comment]
Sounds like same issue i reported in the other thread in regards to the Cree scout unit. The lens just didn't auto activate, but i could still turn it on manually. This was prior to spring update.

**Comment by rasputinoz** [comment]
ok had a play with the modlens_scout.lua and seem to have it working for all recon units.

Can some please download this to trial it.

it belongs in \My Games\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition-expansion1\Integrations\ML\UI\Lenses

Hope this helps



[modlens_scout.zip](https://github.com/Azurency/CQUI_Community-Edition/files/2130381/modlens_scout.zip)

**Comment by Azurency** [comment]
Also opened a PR in @astog repo https://github.com/astog/MoreLenses/pull/25
