### ISSUE TITLE
TechTree does not show

### ISSUE THREAD

**Issue by nikoli280397** [Azurency/CQUI_Community-Edition#339]
Hi great mod. But i cant use it without the techtree. It does not open when i use the mod. I have tried replacing the TechTree file without succes

**Comment by ihendriks** [comment]
Are you playing standard or Rise & Fall? What version of the mod are you using (if from this site, what branch did you download)?

Could you upload your logs and savefile. You can find them in `..\documents\my games\sid meier's civilization vi\`

Thanks.

**Comment by nikoli280397** [comment]
Im not playing R&F. I tried both the steam workshop version and the direct version from Github with same result
[Logs.zip](https://github.com/Azurency/CQUI_Community-Edition/files/2023383/Logs.zip)

**Comment by ihendriks** [comment]
Are you sure you're loading CQUI? In the logs you've sent me it doesn't look like you're loading CQUI at all. You are loading some other mods though.

By the way, what version did you download from here? The `master` branch doesn't work with the Spring patch. You'll need to try [Patch-1.0.0.257](https://github.com/Azurency/CQUI_Community-Edition/archive/Patch-1.0.0.257.zip).

Please try it without any mods as well, as they might conflict.

**Comment by nikoli280397** [comment]
It works now. I downloaded the master branch so that is why it did not work. Thanks
