### ISSUE TITLE
Can't make deals with Joint War/Research Agreement

### ISSUE THREAD

**Issue by Awesomlego** [Azurency/CQUI_Community-Edition#340]
Anytime I'm making a deal with another Civ and click on the option for Joint War or Research Agreement nothing happens. It doesn't go into each column for the Civs like it usually does and there's no indication anything happened besides the audible sound that happens when something goes into a deal. If I haven't out anything else into the deal then I can't accept a deal or anything like that. Other Civs can make deals that include those with me, but I can't with them.

**Comment by ihendriks** [comment]
Are you running the base game, or are you playing with Rise & Fall DLC? And what version of the mod are you using (steam or from this site)?

Could you also please upload your logs and savegame file. You can find them in `..\documents\my games\sid meier's civilization vi\`

Thanks.

**Comment by Awesomlego** [comment]
I'm running the base game but with a decent amount of mods. It just started acting up when I started my most recent game. I'm using the latest version from the Steam Workshop (I had to add in the techtree.lua file from here though).

GitHub is saying that it doesn't support the savegame file type or most of the log files. I uploaded all the log files it would accept.

[Startup.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040346/Startup.log)
[SynthesisLog.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040347/SynthesisLog.log)
[UnitOperations.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040348/UnitOperations.log)
[UserInterface.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040349/UserInterface.log)
[VisManagerErrors.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040350/VisManagerErrors.log)
[Achievements.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040351/Achievements.log)















[ArtDef.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040352/ArtDef.log)
[AStar_APP.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040354/AStar_APP.log)
[AStar_GC.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040355/AStar_GC.log)

[BlockerLog.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040356/BlockerLog.log)


[ctpHttp.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040357/ctpHttp.log)
[CultureBordersLog.txt](https://github.com/Azurency/CQUI_Community-Edition/files/2040358/CultureBordersLog.txt)
[Database.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040359/Database.log)
[DiplomacyDeals.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040360/DiplomacyDeals.log)



[DynGeoLog.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040361/DynGeoLog.log)
[Engine.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040362/Engine.log)
[FiraxisLive.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040363/FiraxisLive.log)






[GameCore.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040364/GameCore.log)
[GameCoreAppConfig.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040365/GameCoreAppConfig.log)




[LoadGameViewState.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040339/LoadGameViewState.log)
[Localization.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040340/Localization.log)
[Lua.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040341/Lua.log)
[Modding.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040342/Modding.log)
[net_connection_debug.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040343/net_connection_debug.log)
[net_message_debug.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040344/net_message_debug.log)


[Renderer.log](https://github.com/Azurency/CQUI_Community-Edition/files/2040345/Renderer.log)

**Comment by ihendriks** [comment]
You can zip them and it'll accept it, but don't worry about it.

It's not functioning right because the steam version isn't up to date with the spring patch.

You can download the latest version from [here](https://github.com/Azurency/CQUI_Community-Edition/archive/Patch-1.0.0.257.zip).

It's always possible that one of your other mods is conflicting, but that's hard to say.

**Comment by llhupp** [comment]
I also saw this with the Expansion1 branch while running R&F plus Spring patch. No other mods.

**Comment by ihendriks** [comment]
Can you upload your logs and save file for me? Thanks

**Comment by llhupp** [comment]
I won't be on that computer for a few days, but I'll try at my next convenience.

**Comment by selfproclaimednerd** [comment]
I can make research alliances through the alliance menu, but not on the trade screen.
Joint wars is not working for me-- same deal as @Awesomlego. I can click it but nothing happens other than the audible click. 

Logs & save file attached as .zips
[logs.zip](https://github.com/Azurency/CQUI_Community-Edition/files/2067647/logs.zip)

[JOHN CURTIN 472 2035 AD.zip](https://github.com/Azurency/CQUI_Community-Edition/files/2067649/JOHN.CURTIN.472.2035.AD.zip)

**Comment by gleesnipeshot** [comment]
I'm also running the base game with 3 other friends all having the issue of can't do joint wars and research agreements. 

Hope this is fixed soon, playing without this mod sucks. Keep up the good work on it.

**Comment by Mysterius** [comment]
Same problem. Base game with all DLC civilizations but **not** R&F.

**Comment by ihendriks** [comment]
The issue has been fixed, but we'll have to wait for Azurency to merge the changes. Sorry for the delay.

**Comment by gleesnipeshot** [comment]
Awesome!! Do you happen to know if the full tech tree not coming up is fixed. I've been using the work around of manually coping the file over?

Sorry for bringing up another issue in this thread. If that's not appropriate just yell at me and I'll go away :) ps thanks for all the work you guys do!!

**Comment by Mysterius** [comment]
Thanks @ihendriks , I applied your commit to my files and it works perfectly :).

**Comment by ihendriks** [comment]
> @gleesnipeshot 
> Awesome!! Do you happen to know if the full tech tree not coming up is fixed. I've been using the work around of manually coping the file over?
> 
> Sorry for bringing up another issue in this thread. If that's not appropriate just yell at me and I'll go away :) ps thanks for all the work you guys do!!

That has been fixed for a while now, but it resides in the `Patch-1.0.0.257` branch and isn't on the steam workshop yet. If you're using R&F it gets a bit complicated and copying files is the only way to do it for now.

> @Mysterius 
> Thanks @ihendriks , I applied your commit to my files and it works perfectly :).

Good to know that it works. It's not my patch though, it's done by @pspjuth
