### ISSUE TITLE
WorldTracker Panel

### ISSUE THREAD

**Issue by FRUM10US** [Azurency/CQUI_Community-Edition#344]
Windows 10 
ver 1.0.0.257
G+K
latest community patch
latest techtree.lua
Everything working fine but no info in worldtracker panel for either Techs or Civics

![40891402-bb928680-677c-11e8-881d-65344fbf360f](https://user-images.githubusercontent.com/39886092/41508749-5dfab838-7241-11e8-826c-232265d5cb37.png)

**Comment by ihendriks** [comment]
We're aware of the issues with the mod at the moment. I've been very busy and haven't been able to do anything for the mod in the last weeks, and I know that Azurancy was busy as well. I'll be able to look into it in at the end of next week. Sorry for the lack of communication either way.

**Comment by FRUM10US** [comment]
Thanks to you and Az for your all-round awesomeness...  :)

**Comment by ihendriks** [comment]
> @pelff 
> Sry, it's not a solution. But it seems it's "just" a broken link between UI and ressources, I do few dev, so is there any way to start resolving it? Can you link us a similar issue so i can make a try to apply the same solution?

Most issues we're aware of are already fixed, just need to push them to the right branches when Azurency is back from his work.

**Comment by Azurency** [comment]
see #283
