### ISSUE TITLE
Unoffical merge: CQUI expansion1 + City Status fix+ Tech fix + diplomacy joint war fix

### ISSUE THREAD

**Issue by HicPuer** [Azurency/CQUI_Community-Edition#350]
I combined following CQUI R&F fixes for my own use. You can download it here: https://www.upload.ee/files/8676602/07.13.2018_R_F_CQUI_expansion1___City_Status_fix__Tech_fix___diplomacy_joint_war_fix.7z.html
Let me know if something is missing or outdated.

Sources:
1. Tech tree and world overview to default UI: https://github.com/Azurency/CQUI_Community-Edition/issues/329#issuecomment-403253007

2. City Status fix: https://github.com/Azurency/CQUI_Community-Edition/issues/283#issuecomment-404058651

3. Diplomacy view / joint war fix: https://github.com/Azurency/CQUI_Community-Edition/issues/283#issuecomment-404364480

**Comment by martin71727** [comment]
Hello! How can i install this fix? Thanks!

**Comment by HicPuer** [comment]
Removed the outdated link. official version is now master, available here: https://github.com/Azurency/CQUI_Community-Edition
Copy mod folder to "My Games\Sid Meier's Civilization VI\Mods", same as any mod.
