### ISSUE TITLE
Mod does not start game, returns to main menu

### ISSUE THREAD

**Issue by miggyboi** [Azurency/CQUI_Community-Edition#365]
With or without any other mod, when the CQUI mod is enabled, I could not start a game. Whenever I start a game, it would start loading and briefly show a "Start Game" text then swiftly come back to the main menu screen. The game works properly without the mod. I download from the new repository, and extracted the .zip file's contents inside the Civ VI game folder (under the folder DLCs, because that is where the other official DLCs are found).

**To Reproduce**
Go to "single player > create game > start game > screen is black with message "Loading. Please Wait..." > Brief "Start Game" in black background where loading message was > returns to main menu

**Expected behavior**

**Screenshots**

**General informations**
 - OS: Windows 10
 - Version 1.0.0.216
 - Expansion Rise and Fall
 - Other mods: none

**Additional context**
Regrettably, I am using a pirated version of the game, specifically the Sid.Meiers.Civilization.VI.Rise.and.Fall-CODEX version of the game

**Comment by ihendriks** [comment]
> I download from the new repository, and extracted the .zip file's contents inside the Civ VI game folder (under the folder DLCs, because that is where the other official DLCs are found).

This is not the right way to install the mod. You need to install it in `Documents\my games\Sid Meier's Civilization VI\Mods`.

If that doesn't work, could you please provide your logs and savegame? Also, do you happen to know what version of the game you are using? Like, the patch version?
