### ISSUE TITLE
Linux/Rise and Fall - No city banners/information/management, world tracker unresponsive, hangs when meeting civ

### ISSUE THREAD

**Issue by axb993** [Azurency/CQUI_Community-Edition#374]
Fresh install, no other mods. Cities have no banners, and when clicked on only show the production menu and the basic city information panel in the bottom right, with the tile/citizen etc buttons removed.

![cqui1](https://user-images.githubusercontent.com/32054734/50329026-82fed100-0549-11e9-9fdc-05a94c76904f.png)

Additionally, clicking the "show/hide world tracker panels" button does nothing. The chat panel is permanently open, and above it is a button that just makes this line appear.

![cqui2](https://user-images.githubusercontent.com/32054734/50329110-d83ae280-0549-11e9-9d24-a4c600cfe8dc.png)

Finally, the game becomes unplayable once meeting another civilization. If met during your turn "Next turn" becomes permanently blocked (as in, "Please wait" flashes for under a second before being stopped as though a unit needs orders, sorry I don't know the term for this and can't really screenshot it). Their icons and information appear but clicking them does nothing, making interacting with them impossible. Even moving a unit to attack theirs and declare war changes nothing (although I haven't been able to actually attack a unit). If the civ meets you during their turn a notification displays but their leader screen does not, leaving the game hanging on "Please wait". Because of this I haven't even been able to test sending envoys.

Everything functions correctly with Rise and Fall disabled (although the button that makes a line is still present, I've actually never used CQUI so I don't know what that's for)

Version 1.0.0.262(164403)
OS: Arch (both native and Steam runtime)

I'm not sure which log files to post but will do so gladly. Any help is greatly appreciated :)

**Comment by ghost** [comment]
+1 also experiencing these issues. It's likely just because the authors haven't made the updates to fix it for linux with R&F yet. After all they only just released the patch that brought all the other updates to the platform.

**Comment by xeruf** [comment]
Are you using my unofficial "CQUI Linux" or the original?

**Comment by axb993** [comment]
This was the original, just tried your version @Xerus2000 but no difference

**Comment by xeruf** [comment]
Yeah, should be. You gotta fix it yourself apparently, afaik the lead developer stopped working on this.

**Comment by mateuszkitlas** [comment]
@Xerus2000 your version seems to have the same hash as main version. Can this cause any problem?

**Comment by ghost** [comment]
@Xerus2000 The lead dev stopped working on making CQUI work for linux or the project in general? Either way what was their reasoning? Is nobody else stepping in?

**Comment by ihendriks** [comment]
@Cether-Skye @Xerus2000 Haven't heard of him in months. He was very busy with work at the time and I reckon that hasn't changed.

I tried to pick up some pieces but I'm very busy myself and am not well known enough with how CIV works to fix some of the issues, so I kind of left it as is as well.

That goes for the project in general, not just linux/mac.

**Comment by sinqbad** [comment]
Can confirm that the original and @Xerus2000 both don't work on linux

4.20.0-arch1-1-ARCH

**Comment by hartmark** [comment]
NTFS is case-insensitive so on linux you run most likely on a case-sensitive filesystem. There's some wrong casings in the code. After some googling I found this fix.

```
"steam-install-folder"/steamapps/workshop/content
sudo mkfs.vfat -C -F 32 civ6-mods.img 1048576
mv 289070 289070.old
mkdir 289070
```

Add this to your /etc/fstab:
`
"steam-install-folder"/steamapps/workshop/content/civ6-mods.img    "steam-install-folder"/steam/steamapps/workshop/content/289070   vfat    loop,iocharset=iso8859-1,uid="your username",gid="your group",fmask=113,dmask=002 0 0`

```
sudo mount 289070
rsync -av 289070.old/* 289070/
```

**Comment by mibli** [comment]
> NTFS is case-insensitive so on linux you run most likely on a case-sensitive filesystem. There's some wrong casings in the code. After some googling I found this fix.
> ...

Does it work for You on linux now @hartmark ?
Castings should be easy to fix if it's just that.

**Comment by hartmark** [comment]
Yeah it seems to be working. I agree it should be easy to fix, alas I haven't had time to look at it myself.

**Comment by mibli** [comment]
> `sudo mkfs.vfat -C -F 32 civ6-mods.img 1048576`

`sudo` should not be necessary, because Youre creating a file essentially, and root has access to it anyway, so should be available at boot.

> `"steam-install-folder"/steamapps/workshop/content/civ6-mods.img "steam-install-folder"/steam/steamapps/workshop/content/289070 vfat loop,iocharset=iso8859-1,uid="your username",gid="your group",fmask=113,dmask=002 0 0`

has extra `steam/`, also quotes are missleading (if You have quotes, the mount will fail with confusing message

```
STEAM_INSTALL_FOLDER/steamapps/workshop/content/civ6-mods.img STEAM_INSTALL_FOLDER/steamapps/workshop/content/289070 vfat loop,iocharset=iso8859-1,uid=YOUR_USERNAME,gid=YOUR_GROUP,fmask=113,dmask=002 0 0
```

It's a good find, thank You very much.
I can confirm this workaround working on my end too.

**Comment by PureTryOut** [comment]
Ah damn I literally just found this mod and was wondering why the game was so buggy all of a sudden. I'm not going to make some FAT32 image and mount it, just for this game. Is there not a fork somewhere that is more updated and has fixed the capitalizing issue?

**Comment by xeruf** [comment]
https://github.com/Azurency/CQUI_Community-Edition/network

Someone would have to fully take over the project sooner or later, which is some work. I think I could get into that, but I play Civ too little right now and have a whole bunch of other projects. Basically, either someone is is into enough to do it or someone would have to pay for the development ^^

**Comment by hartmark** [comment]
I can buy you one beer or two :)

**Comment by Azurency** [comment]
It's an old issue. If there's still problem with Linux and the latest update, can you open a new issue please.
