### ISSUE TITLE
Whole interface is unfunctional

### ISSUE THREAD

**Issue by tomas-hruby** [Azurency/CQUI_Community-Edition#375]
**Describe the bug**
The whole interface including main menu doesnt work. The only option is to Alt+F4.
**To Reproduce**
Start the game

**Expected behavior**
Buttons working

**Screenshots**
![bez nazvu](https://user-images.githubusercontent.com/46090576/50386146-aeb4bf00-06e1-11e9-88ae-bdb617e0fba9.png)

**General informations**
 - OS: Win10
 - Version 1.0.0.262
 - Expansion Rise and Fall
 - Other mods: no

**Comment by Kratzwurst** [comment]
Yeah confirmed, i played a game. after 10 rounds the gui is completely gone

**Comment by MRpEGGasus** [comment]
anyone found solutions yet?

**Comment by sparrow8332** [comment]
I Played for over 200 turns and not a single issue

**Comment by MRpEGGasus** [comment]
turnsout it was about my 'worldinput.lua'. i left a typo in the codes while changing hotkey of my choice.. hope this helps
