### ISSUE TITLE
Is it possible to save the CQUI options after I customize them?

### ISSUE THREAD

**Issue by Nihimon** [Azurency/CQUI_Community-Edition#377]
Whenever I restart the game client, I have to manually reset the CQUI options back to my preferred values.

Is it possible to edit a configuration file or something and make these changes persistent?

**Comment by wayneb64** [comment]
Copy the file cqui_settings to cqui_settings_local and modify that with your settings. 

Search for the former, mine was here:

H:\SteamLibrary\SteamApps\workshop\content\289070\1125169247\Assets

**Comment by Nihimon** [comment]
Found the file, thanks!

**Comment by Azurency** [comment]
Added the `AffectsSaveGame` back in `modinfo` so it should save with each savegame you have.
