### ISSUE TITLE
Support for Gathering Storm???

### ISSUE THREAD

**Issue by wayneb64** [Azurency/CQUI_Community-Edition#379]
Is CQUI dead or just sleeping? With GS out now is there any chance this mod will be updated to support it?

I waited quite some time to by RF as I didn't want to give up CQUI. I hear some features of CQUI are in GS but I am not sure which or how many. 

I need some information before I make a decision on buying GS and abandoning CQUI or waiting.

**Comment by alexeyOnGitHub** [comment]
see https://github.com/Azurency/CQUI_Community-Edition/issues/380

**Comment by wayneb64** [comment]
Awesome!
