### ISSUE TITLE
'Toggle yields ON by default' is backwards in the CQUI options menu

### ISSUE THREAD

**Issue by ubereffect** [Azurency/CQUI_Community-Edition#394]
Now that Gathering Storm has Yields toggled ON by default, it seems that CQUI has it backwards. 'Toggle yields ON by default' in the CQUI options menu actually turns them OFF when selected, and ON when unselected.

 - OS: Windows 10
 - Version: 1.0.0.290
 - Expansions: All expansions and DLC, including Rise & Fall, and Gathering Storm
 - Other mods: None

**Comment by paveldesigner** [comment]
Have the same problem. OS and game versions are the same too.

**Comment by Azurency** [comment]
Fixed in https://github.com/Azurency/CQUI_Community-Edition/commit/ba6e1509123be91c2a64c6b3d3998ddc44d0c49e
