### ISSUE TITLE
April 2nd update has broken CQUI

### ISSUE THREAD

**Issue by gitgotgit** [Azurency/CQUI_Community-Edition#396]
**Describe the bug**

As soon as I meet another Civ my whole HUD overlay disappears (only thing that works is ESC to quit the game. 

Also the leader ribbons (top right) are not displaying science per turn or military strength (before the HUD disappears).

**To Reproduce**
Start a new game and then meet another CIV, so far the fault happens every time.

Already several posts on the Steam Worksop community reporting the same problem.

**General informations**
 - Windows 10
 - Version 1809
Mods:
- Gathering Storm - The Antarctic Late Summer Game Update
- CQUI
- Really Advanced Setup Lite (used to give me some scouts to test this quickly)

**Save game and logs**
[Files.zip](https://github.com/Azurency/CQUI_Community-Edition/files/3038168/Files.zip)

**Screenshots**
![Screenshot_2019-04-03](https://user-images.githubusercontent.com/9074900/55471962-e1d0ed80-5602-11e9-98d9-e57f49482fa7.jpg)

**Comment by kkanoee** [comment]
Can confirm I have the same issue here

**Comment by devbaj** [comment]
Same issue here, but happens whenever a leader dialogue is trying to show up (trades, denouncements, etc)

**Comment by ihendriks** [comment]
This has been picked up in issue #397 

You can track progress there as well if you're interested.

**Comment by Matakor** [comment]
Is there a temporary fix for this?
