### ISSUE TITLE
Black Text for Buying with Gold/faith in City View

### ISSUE THREAD

**Issue by AlecBraithwaite** [Azurency/CQUI_Community-Edition#399]
**Describe the bug**
The numbers for buying buildings or units with gold or faith are black, which makes them almost impossible to read. Is there a setting for this somewhere?

**To Reproduce**
Play with Any civ

**Expected behavior**
White text instead of black

**Screenshots**
https://i.imgur.com/G4CEmT2.png

**General informations**
Windows, No other mods

**Save game and logs**
[JADWIGA 1 4000 BC.Civ6Save.txt](https://github.com/Azurency/CQUI_Community-Edition/files/3099024/JADWIGA.1.4000.BC.Civ6Save.txt)

**Comment by op1ekun** [comment]
Same here, I've just downloaded the mod, but it's impossible to use it in its current state :(

**Comment by ubereffect** [comment]
Issue still present in latest version posted on GitHub just under 12 hours ago. I'm running a fresh game, with no other mods, and I've unsubscribed to Steam version of CQUI to avoid conflict.

**Comment by ubereffect** [comment]
To quote eudaimonia, the author of Concise UI:

here's some examples for how to set color use new functions:

old version:
1. Controls.instance:SetColor(0xFFFFFFFF);
2. Controls.instance:SetColor("COLOR_RED");
3. Controls.instance:SetColorByName("RED");

new version:
1. Controls.instance:SetColor(UI.GetColorValueFromHexLiteral(0xFFFFFFFF));
2. Controls.instance:SetColor(UI.GetColorValue("COLOR_RED"));
3. Controls.instance:SetColorByName("RED");

**Comment by ubereffect** [comment]
Probably a better reference would be to search the change log posted at [Azurency/Civ6-UIFiles@14e657f](https://github.com/Azurency/Civ6-UIFiles/commit/14e657fc569b99e6f1166bd175ba67edea5dc3fd) for the word color.

Seems like the most annoying bug I've encountered so far, and likely the easiest to fix.
