### ISSUE TITLE
Request: Hardcoded text

### ISSUE THREAD

**Issue by 8h42** [Azurency/CQUI_Community-Edition#4]
Hi Sparrow,

A few strings are hardcoded.
Woudl you make it possible to translate them?

-----
1. Improved Deal Screen
![improved deal screen](https://user-images.githubusercontent.com/11933188/30064308-485f4e34-928c-11e7-8462-7398dcc9cdfb.png)

(1) DEAL TERMS

cf.
\Integrations\IDS\diplomacydealview.xml
Line: 189
`                <Label ID="DealTermsLabel" String="DEAL TERMS" Anchor="C,T" Style="FontBoldFlair26" FontStyle="glow" Color0="GoldMetalDark"  Color1="0,0,0,200"/>`

(2) - Cede

cf.
\Integrations\IDS\diplomacydealview.lua
Line: 1917
`      button.IconText:SetText(button.IconText:GetText() .. '[COLOR_Civ6Green] - Cede[ENDCOLOR]');`

(3) - Return

cf.
\Integrations\IDS\diplomacydealview.lua
Line: 1922
`        button.IconText:SetText(button.IconText:GetText() .. '[COLOR_Civ6Red] - Return[ENDCOLOR]');`

-----
2. Unit Report Screen
![unit report screen](https://user-images.githubusercontent.com/11933188/30064382-8404b4ba-928c-11e7-9286-e2b4d7992e2b.png)

(1) Promotion Available

cf.
\Integrations\URS\reportscreen.xml
Line: 1125
`            <Image Offset="0,-1" Texture="Stats32" Size="32,32" Anchor="R,C" ToolTip="Promotion Available" Icon="ICON_PROMOTION"/>`

(2) In Formation

cf.
\Integrations\URS\reportscreen.xml
Line: 1135, 1173, 1244, 1280, 1320

`          <Image ID="Formation" Hidden="1" Offset="0,-1" Texture="Stats32" Size="32,32" Anchor="R,C" ToolTip="In Formation" Icon="ICON_UNITCOMMAND_ENTER_FORMATION"/>`

**Comment by sparrow8332** [comment]
Check "Deal View" now and let me know if that part changes fine and the translation is ok

**Comment by 8h42** [comment]
It works fine!
![improved deal screen 2](https://user-images.githubusercontent.com/11933188/30080203-b5bfef48-92bd-11e7-9d64-cef19da73c4d.png)

**Comment by sparrow8332** [comment]
Great is the translation ok >?

**Comment by 8h42** [comment]
Yeah, no problem.

**Comment by 8h42** [comment]
I could translate the strings of DEAL TERMS, Promotion Available and In Formation.
I have no idea how to tweak the diplomacydealview.lua, though.

[Integrations.zip](https://github.com/sparrow8332/CQUI_Community-Edition/files/1282934/Integrations.zip)

**Comment by Azurency** [comment]
the Cede and Return are hard coded here https://github.com/sparrow8332/CQUI_Community-Edition/blob/10035b712233f58c8b6d81d63ec28b9c2a519d49/Integrations/IDS/diplomacydealview.lua#L1917
and here https://github.com/sparrow8332/CQUI_Community-Edition/blob/10035b712233f58c8b6d81d63ec28b9c2a519d49/Integrations/IDS/diplomacydealview.lua#L1922

They should be replaced by `Locale.Lookup("SOME_LOC_KEY_FOR_CEDE_OR_RETURN" )`

**Comment by 8h42** [comment]
Thanks, Azurency.

However, I'm not sure where to insert the code.
Could you write the entire line?

cf.
LOC_IDS_DEAL_CEDE
LOC_IDS_DEAL_RETURN

**Comment by 8h42** [comment]
I found other texts.
![duplicate](https://user-images.githubusercontent.com/11933188/30158596-ba0c9e04-9400-11e7-9110-32839981c9e3.png)

1. Suzerain of
https://github.com/sparrow8332/CQUI_Community-Edition/blob/10035b712233f58c8b6d81d63ec28b9c2a519d49/Integrations/IDS/diplomacydealview.lua#L1610

2. (Duplicate)
https://github.com/sparrow8332/CQUI_Community-Edition/blob/10035b712233f58c8b6d81d63ec28b9c2a519d49/Integrations/IDS/diplomacydealview.lua#L1765

3. (Untradeable)
https://github.com/sparrow8332/CQUI_Community-Edition/blob/10035b712233f58c8b6d81d63ec28b9c2a519d49/Integrations/IDS/diplomacydealview.lua#L1768

**Comment by Azurency** [comment]
Yes, I believe this integration was not translated, there should be even more texts that are not translated.

So to answer you question the entire line should be something like this (ex. for _cede_) : 
```Lua
button.IconText:SetText(button.IconText:GetText() .. '[COLOR_Civ6Green] - ' .. Locale.Lookup("LOC_IDS_DEAL_CEDE") .. '[ENDCOLOR]'); 
```

`..` is for concatenation and you juste have to place `Locale.Lookup(...)` correctly.

Another example for _(Duplicate)_, it would be : 
```Lua
tooltipAddedText = ' (' .. Locale.Lookup("LOC_IDS_DEAL_DUPLICATE") .. ')'); 
```
and so on

**Comment by 8h42** [comment]
Thank you again.
There is another one.
https://github.com/Azurency/CQUI_Community-Edition/blob/10035b712233f58c8b6d81d63ec28b9c2a519d49/Integrations/IDS/diplomacydealview.lua#L1556

I managed to replace the hardcoded texts.
[CQUI_Community-Edition-summer-2017_experiment.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1287576/CQUI_Community-Edition-summer-2017_experiment.zip)

Updated files:

- Assets/Text/cqui_text_general.xml
- Integrations/IDS/diplomacydealview.lua
- Integrations/IDS/diplomacydealview.xml
- Integrations/IDS/Text/ids_text.xml
- Integrations/URS/reportscreen.xml
- Integrations/URS/Text/urs_text.xml

I hope someone tests it.

**Comment by 8h42** [comment]
for the latest steam version
[1125169247_CQUI - Community Edition_2017.09.08_experiment.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1287709/1125169247_CQUI.-.Community.Edition_2017.09.08_experiment.zip)

**Comment by sparrow8332** [comment]
Will be home later today and give it a run through :-)

**Comment by deggesim** [comment]
As I gave my contribution for italian translation to CQUI, I can help here too.

**Comment by ohhhhhhhYi** [comment]
hi,I test it in Traditional Chinese already
everything looks good # @8h42

**Comment by 8h42** [comment]
@ohhhhhhhYi
Glad to hear that.

-----
citypanel.lua

1. from Population
https://github.com/Azurency/CQUI_Community-Edition/blob/10035b712233f58c8b6d81d63ec28b9c2a519d49/Assets/UI/Panels/citypanel.lua#L410

2. Religious Minorities
https://github.com/Azurency/CQUI_Community-Edition/blob/10035b712233f58c8b6d81d63ec28b9c2a519d49/Assets/UI/Panels/citypanel.lua#L447

3. Pillaged
https://github.com/Azurency/CQUI_Community-Edition/blob/10035b712233f58c8b6d81d63ec28b9c2a519d49/Assets/UI/Panels/citypanel.lua#L459
https://github.com/Azurency/CQUI_Community-Edition/blob/10035b712233f58c8b6d81d63ec28b9c2a519d49/Assets/UI/Panels/citypanel.lua#L471


for the latest steam version (2017.09.21)
[1125169247_Community Quick User Interface_2017.09.21_experiment.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1320762/1125169247_Community.Quick.User.Interface_2017.09.21_experiment.zip)

Updated files:
- Assets/Text/cqui_text_general.xml
- Assets/UI/Panels/citypanel.lua

Screen Shot:
![ss](https://user-images.githubusercontent.com/11933188/30690784-482dec1a-9f00-11e7-8101-01e6c81c6d70.jpg)

I'll upload Japanese translation if everything goes well.

**Comment by 8h42** [comment]
Another one.

`The city will expand to this tile upon the next cultural borders growth`

Screen Shot:
![next_plot](https://user-images.githubusercontent.com/11933188/30770862-eb4079a6-a075-11e7-8661-bb417c12578e.png)



- citybannermanager.xml

https://github.com/Azurency/CQUI_Community-Edition/blob/ff4533853f1270fcfdf0469102426903496b997e/Assets/UI/WorldView/citybannermanager.xml#L21
https://github.com/Azurency/CQUI_Community-Edition/blob/ff4533853f1270fcfdf0469102426903496b997e/Assets/UI/WorldView/citybannermanager.xml#L22

- plotinfo.xml

https://github.com/Azurency/CQUI_Community-Edition/blob/ff4533853f1270fcfdf0469102426903496b997e/Assets/UI/WorldView/plotinfo.xml#L21
https://github.com/Azurency/CQUI_Community-Edition/blob/ff4533853f1270fcfdf0469102426903496b997e/Assets/UI/WorldView/plotinfo.xml#L22

**Comment by 8h42** [comment]
Thank you for merging my branch!
