### ISSUE TITLE
[Bug] Encampment Ranged Strikes

### ISSUE THREAD

**Issue by ubereffect** [Azurency/CQUI_Community-Edition#400]
**Describe the bug**
If a city has an encampment with walls and an enemy unit comes within range of both the city and the encampment, clicking the red target above the encampment doesn't allow you to target the enemy within range, without first clicking the red target above the city.

**Clarification**
If there's an enemy unit within range of the encampment, but none within range of the city, clicking the red target above the encampment works as expected.

If there's an enemy unit within range of both the city and the encampment, the red target above the encampment will not work at first. Once you click the red target above the city or click the ranged strike notification in the side bar (no need to fire), you can then click the red target above the encampment, and it will work.

**To Reproduce**
Build a city with walls and an encampment, and wait to be attacked. Building near a barb camp does the trick. Declaring war should work just as well.

**Expected behavior**
Clicking the red target above an encampment should work right away, from the very start of your turn. There should be no need to switch to the city and back. Vanilla works as expected, tested the same saved games with and without CQUI (every test done with no other active mods).

**General informations**
 - OS: Windows 10
 - Version: 1.0.0.317
 - Expansions: All expansions and DLC, including Rise & Fall, and Gathering Storm
 - Other mods: none

**Save game and logs**
Attached 2 saved game files. Renamed auto-saves, so both are very start of respective turns. Issue only happens when enemy unit is out of city range, but within range of the encampment. I turned off the setting for affects saved games, so I could test with and without CQUI.
[In City Range.zip](https://github.com/Azurency/CQUI_Community-Edition/files/3145030/In.City.Range.zip)
[Out of City Range.zip](https://github.com/Azurency/CQUI_Community-Edition/files/3145031/Out.of.City.Range.zip)

**Additional context**
This bug was first reported by bgeesy, then confirmed by Stylianos in the Steam Workshop comments section. The above saved game files are from my confirming this same bug.

**Comment by Azurency** [comment]
This looks just like a visual bug, in both saves I CAN select the district range attack, but if I hover a unit or a city banner it reset the Lens and we can't see the "range attack UI" anymore although I can still click an ennemi unit and it fires.

I'll fix this bug as soon as possible.

**Comment by Azurency** [comment]
Should be fixed in 10d87bc17ec4e1bb2094bad6ece330a2cdb36258

**Comment by ubereffect** [comment]
Looks like that fixed it. I just reloaded my save with the updated CQUI. Works as expected now.
