### ISSUE TITLE
Apocalypse mode (New Frontier) : cannot sacrifice units to volcanoes

### ISSUE THREAD

**Issue by UltraDiuve** [Azurency/CQUI_Community-Edition#425]
Not sure if this is the relevant repo to log this issue. I ran into it in my first Apocalypse game with the New Frontier pass.

When trying to sacrifice a unit during the Appease the Gods competition, the user interface does not allow to select the unit to sacrifice.

To reproduce:
1- launch a game with CQUI mod as the only activated mod, with Apocalypse option activated
2- wait for an Appease the gods competition
3- have a Soothsayer unit and a regular military unit adjacent to a volcano
4- select the Soothsayer unit, and click on the Sacrifice adjacent unit action button
5- it is not possible to select the military unit to sacrifice

Expected behavior
At step 5-, it should be possible to select the military unit to sacrifice (selectable units tiles should be highlighted green), and then have the sacrifice proceeded.

**Screenshots**
Screenshot not really relevant.

**General informations**
 - OS: Windows 10, civ 6 from Steam
 - Version: 1.0.2.39
 - Expansion: Gathering Storm with New frontier pass as of July 2020
 - Other mods: None, only CQUI activated.

I managed to fix this issue by manually transfering code from the core worldinput.lua file to the mod corresponding file.
Seems to work, but no thorough test has been run for side effects.

**Comment by UltraDiuve** [comment]
[worldinput.txt](https://github.com/Azurency/CQUI_Community-Edition/files/4922098/worldinput.txt)

Could not find a way to attached the modified file as is, had to rename it to .txt. This file should be put in the Assets/UI/ folder.

I would gladly create a pull request if that would be the proper way.

**Comment by Sorxus** [comment]
This version of CQUI isn't maintained anymore, try this one:
https://github.com/civfanatics/CQUI_Community-Edition

**Comment by UltraDiuve** [comment]
Thanks for the information @Sorxus . It looks like the issue has been fixed (and many other things with it) on this other repo.

I close this issue.
