### ISSUE TITLE
Repeat trade route not working

### ISSUE THREAD

**Issue by Azurency** [Azurency/CQUI_Community-Edition#82]
<a href="https://github.com/thyeestes"><img src="https://avatars1.githubusercontent.com/u/21059883?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thyeestes](https://github.com/thyeestes)**
_Thursday Feb 23, 2017 at 15:42 GMT_
_Originally opened as https://github.com/CQUI-Org/cqui/issues/322_

----

When I tick the option to repeat a trade route there will still be a popup to ask for the destination of the trade route when the previous one is finished.

**Comment by Azurency** [comment]
<a href="https://github.com/JHCD"><img src="https://avatars3.githubusercontent.com/u/12496340?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JHCD](https://github.com/JHCD)**
_Friday Feb 24, 2017 at 21:23 GMT_

----

I have tested it in my actual game.

CiV VI: Patch 110
CQUI: Build of 24.02.2017

Here is my Trading Screen:
![trade_routes](https://cloud.githubusercontent.com/assets/12496340/23321545/4c084386-fae0-11e6-983b-f0304a14ee8d.jpg)

Do you have this red arrow beside your repeating route?

**Update**: Looks like it's broken after reload the game.

**Comment by Azurency** [comment]
<a href="https://github.com/chaorace"><img src="https://avatars2.githubusercontent.com/u/6462592?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chaorace](https://github.com/chaorace)**
_Saturday Feb 25, 2017 at 01:07 GMT_

----

This is a bug in Better Trade Screen, paging @Astog

**Comment by Azurency** [comment]
<a href="https://github.com/astog"><img src="https://avatars3.githubusercontent.com/u/9371650?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [astog](https://github.com/astog)**
_Saturday Feb 25, 2017 at 03:49 GMT_

----

Even after the reload the game it should be working. I have been meaning to fix this issue for a while, but haven't found the time between my job and college.

**Comment by astog** [comment]
@Azurency This is fixed in my summer update

**Comment by Azurency** [comment]
Great, I'll close this then as your latest update is integrated here.
