### ISSUE TITLE
Bug: Can't open Policies Screen

### ISSUE THREAD

**Issue by snozzle21** [Azurency/CQUI_Community-Edition#9]
can't open the Policies screen :(.  Sound triggers, but screen never appears.  Other screens appear just fine so far.  Thank you!

**Comment by snozzle21** [comment]
No other mods are used.

**Comment by Azurency** [comment]
I believe things are different on Mac OS, it required a whole other branch on the original cqui repo https://github.com/CQUI-Org/cqui/tree/OSX-Linux so I think the changes will be ported after everything look fine on windows

**Comment by snozzle21** [comment]
Thank for the reply.  Hope it will be ported soon.
